<?php

use Illuminate\Database\Seeder;

class DesignationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('designations')->delete();
        \DB::table('designations')->insert(array(
            0   =>
            array(
                'id'              => 1,
                'name'            => 'Faculty Member',
                'bangla_name'     => 'ফ্যাকাল্টি মেম্বার',
                'short_name'      => 'FM',
                'department_id'   => 1,
                'hierarchy_level' => 100,
                'rank_id'         => 4,
                'created_at'      => null,
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            1   =>
            array(
                'id'              => 2,
                'name'            => 'Deputy Director',
                'bangla_name'     => 'উপ - পরিচালক ( প্রশাসন )',
                'short_name'      => 'DDA',
                'department_id'   => 1,
                'hierarchy_level' => 3,
                'rank_id'         => 1,
                'created_at'      => null,
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            2   =>
            array(
                'id'              => 3,
                'name'            => 'Research Director',
                'bangla_name'     => 'পরিচালক ( গবেষণা )',
                'short_name'      => 'RD',
                'department_id'   => 1,
                'hierarchy_level' => 1,
                'rank_id'         => 1,
                'created_at'      => null,
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            3   =>
            array(
                'id'              => 4,
                'name'            => 'Project Director',
                'bangla_name'     => 'পরিচালক ( প্রকল্প )',
                'short_name'      => 'PD',
                'department_id'   => 2,
                'hierarchy_level' => 1,
                'rank_id'         => 1,
                'created_at'      => null,
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            4   =>
            array(
                'id'              => 5,
                'name'            => 'JR Accounts Officer',
                'bangla_name'     => '',
                'short_name'      => 'JAO',
                'department_id'   => 3,
                'hierarchy_level' => 100,
                'rank_id'         => 4,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            5   =>
            array(
                'id'              => 6,
                'name'            => 'Accounts Officer',
                'bangla_name'     => '',
                'short_name'      => 'AO',
                'department_id'   => 3,
                'hierarchy_level' => 100,
                'rank_id'         => 3,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            6   =>
            array(
                'id'              => 7,
                'name'            => 'Sr Accounts Officer',
                'bangla_name'     => '',
                'short_name'      => 'SAO',
                'department_id'   => 3,
                'hierarchy_level' => 100,
                'rank_id'         => 2,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            7   =>
            array(
                'id'              => 8,
                'name'            => 'Jr IT Officer',
                'bangla_name'     => '',
                'short_name'      => 'JITO',
                'department_id'   => 4,
                'hierarchy_level' => 100,
                'rank_id'         => 4,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            8   =>
            array(
                'id'              => 9,
                'name'            => 'IT Officer',
                'bangla_name'     => '',
                'short_name'      => 'ITO',
                'department_id'   => 4,
                'hierarchy_level' => 100,
                'rank_id'         => 3,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            9   =>
            array(
                'id'              => 10,
                'name'            => 'Senior IT Officer',
                'bangla_name'     => '',
                'short_name'      => 'SITO',
                'department_id'   => 4,
                'hierarchy_level' => 100,
                'rank_id'         => 2,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            10  =>
            array(
                'id'              => 11,
                'name'            => 'Jr HR Executive',
                'bangla_name'     => '',
                'short_name'      => 'JHRE',
                'department_id'   => 5,
                'hierarchy_level' => 100,
                'rank_id'         => 4,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            11  =>
            array(
                'id'              => 12,
                'name'            => 'Senior HR Executive',
                'bangla_name'     => '',
                'short_name'      => 'SHRE',
                'department_id'   => 5,
                'hierarchy_level' => 100,
                'rank_id'         => 2,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            12  =>
            array(
                'id'              => 13,
                'name'            => 'Asst. Director Project',
                'bangla_name'     => 'সহঃ পরিচালক ( প্রকল্প )',
                'short_name'      => 'ADP',
                'department_id'   => 2,
                'hierarchy_level' => 4,
                'rank_id'         => 2,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            13  =>
            array(
                'id'              => 14,
                'name'            => 'Joint Director Project',
                'bangla_name'     => 'যুগ্ম পরিচালক ( প্রকল্প )',
                'short_name'      => 'JDP',
                'department_id'   => 2,
                'hierarchy_level' => 2,
                'rank_id'         => 1,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            14  =>
            array(
                'id'              => 15,
                'name'            => 'Deputy Director Project',
                'bangla_name'     => 'উপ - পরিচালক ( প্রকল্প )',
                'short_name'      => 'DDP',
                'department_id'   => 2,
                'hierarchy_level' => 3,
                'rank_id'         => 1,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            15  =>
            array(
                'id'              => 16,
                'name'            => 'Asst Director General',
                'bangla_name'     => 'সহঃ মহাপরিচালক',
                'short_name'      => 'ADG',
                'department_id'   => 2,
                'hierarchy_level' => 100,
                'rank_id'         => 1,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            16  =>
            array(
                'id'              => 17,
                'name'            => 'Director General',
                'bangla_name'     => 'মহাপরিচালক',
                'short_name'      => 'DG',
                'department_id'   => 9,
                'hierarchy_level' => 0,
                'rank_id'         => 1,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            17  =>
            array(
                'id'              => 18,
                'name'            => 'Asst. Director Research',
                'bangla_name'     => 'সহঃ পরিচালক ( গবেষণা )',
                'short_name'      => 'ADR',
                'department_id'   => 1,
                'hierarchy_level' => 4,
                'rank_id'         => 1,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            18  =>
            array(
                'id'              => 19,
                'name'            => 'Joint Director Research',
                'bangla_name'     => 'যুগ্ম পরিচালক ( গবেষণা )',
                'short_name'      => 'JDR',
                'department_id'   => 1,
                'hierarchy_level' => 2,
                'rank_id'         => 1,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            19  =>
            array(
                'id'              => 20,
                'name'            => 'Deputy Director Research',
                'bangla_name'     => 'উপ - পরিচালক ( গবেষণা )',
                'short_name'      => 'DDR',
                'department_id'   => 1,
                'hierarchy_level' => 3,
                'rank_id'         => 1,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            20  =>
            array(
                'id'              => 21,
                'name'            => 'Director HR',
                'bangla_name'     => 'পরিচালক ( সংস্থাপন )',
                'short_name'      => 'DIRHR',
                'department_id'   => 1,
                'hierarchy_level' => 1,
                'rank_id'         => 1,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            21  =>
            array(
                'id'              => 22,
                'name'            => 'Director Research',
                'bangla_name'     => 'পরিচালক ( গবেষণা )',
                'short_name'      => 'DIRR',
                'department_id'   => 1,
                'hierarchy_level' => 1,
                'rank_id'         => 1,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            22  =>
            array(
                'id'              => 23,
                'name'            => 'Director Project',
                'bangla_name'     => 'পরিচালক ( প্রকল্প )',
                'short_name'      => 'DIRP',
                'department_id'   => 1,
                'hierarchy_level' => 1,
                'rank_id'         => 1,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            23  =>
            array(
                'id'              => 24,
                'name'            => 'Director Hostel',
                'bangla_name'     => 'পরিচালক ( হোস্টেল )',
                'short_name'      => 'DIRH',
                'department_id'   => 1,
                'hierarchy_level' => 1,
                'rank_id'         => 1,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            24  =>
            array(
                'id'              => 25,
                'name'            => 'Hostel Manager',
                'bangla_name'     => 'হোস্টেল ম্যানেজার',
                'short_name'      => 'HM',
                'department_id'   => 8,
                'hierarchy_level' => 100,
                'rank_id'         => 1,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            25  =>
            array(
                'id'              => 26,
                'name'            => 'Director Admin',
                'bangla_name'     => 'পরিচালক ( প্রশাসন )',
                'short_name'      => 'DA',
                'department_id'   => 9,
                'hierarchy_level' => 1,
                'rank_id'         => 1,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            26  =>
            array(
                'id'              => 27,
                'name'            => 'Director Training',
                'bangla_name'     => 'পরিচালক ( প্রশিক্ষণ )',
                'short_name'      => 'DT',
                'department_id'   => 7,
                'hierarchy_level' => 1,
                'rank_id'         => 1,
                'created_at'      => '2019-02-07 21:30:06',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            27  =>
            array(
                'id'              => 28,
                'name'            => 'Joint Director Training',
                'bangla_name'     => 'যুগ্ম পরিচালক ( প্রশিক্ষণ )',
                'short_name'      => 'JDT',
                'department_id'   => null,
                'hierarchy_level' => 2,
                'rank_id'         => 1,
                'created_at'      => '2019-05-28 14:50:16',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            28  =>
            array(
                'id'              => 29,
                'name'            => 'Asst. Director Training',
                'bangla_name'     => 'সহঃ পরিচালক ( প্রশিক্ষন )',
                'short_name'      => 'ADT',
                'department_id'   => null,
                'hierarchy_level' => 4,
                'rank_id'         => 1,
                'created_at'      => '2019-05-28 14:50:57',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            29  =>
            array(
                'id'              => 30,
                'name'            => 'Asst. Director Training (Sports)',
                'bangla_name'     => 'সহঃ পরিচালক ( প্রশিক্ষন ) - খেলা',
                'short_name'      => 'ADTS',
                'department_id'   => null,
                'hierarchy_level' => 4,
                'rank_id'         => 1,
                'created_at'      => '2019-05-28 14:51:13',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            30  =>
            array(
                'id'              => 31,
                'name'            => 'Director Agriculture and Environment',
                'bangla_name'     => 'পরিচালক ( কৃষি ও পরিবেশ )',
                'short_name'      => 'DAE',
                'department_id'   => null,
                'hierarchy_level' => 1,
                'rank_id'         => 1,
                'created_at'      => '2019-05-28 15:24:06',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            31  =>
            array(
                'id'              => 32,
                'name'            => 'Joint Director Agriculture and Environment',
                'bangla_name'     => 'যুগ্ম পরিচালক ( কৃষি ও পরিবেশ )',
                'short_name'      => 'JDAE',
                'department_id'   => null,
                'hierarchy_level' => 2,
                'rank_id'         => 1,
                'created_at'      => '2019-05-28 15:25:30',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            32  =>
            array(
                'id'              => 33,
                'name'            => 'Deputy Director Agriculture and Environment',
                'bangla_name'     => 'উপ - পরিচালক ( কৃষি ও পরিবেশ )',
                'short_name'      => 'DDAE',
                'department_id'   => null,
                'hierarchy_level' => 3,
                'rank_id'         => 1,
                'created_at'      => '2019-05-28 15:25:54',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            33  =>
            array(
                'id'              => 34,
                'name'            => 'Asst. Director Agriculture and Environment',
                'bangla_name'     => 'সহঃ পরিচালক ( কৃষি ও পরিবেশ )',
                'short_name'      => 'ADAE',
                'department_id'   => null,
                'hierarchy_level' => 4,
                'rank_id'         => 1,
                'created_at'      => '2019-05-28 15:26:18',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            34  =>
            array(
                'id'              => 35,
                'name'            => 'Joint Director Rural Economy & Management',
                'bangla_name'     => 'যুগ্ম পরিচালক ( পল্লী অর্থনীতি ও ব্যবস্থাপনা )',
                'short_name'      => 'JDREM',
                'department_id'   => null,
                'hierarchy_level' => 2,
                'rank_id'         => 1,
                'created_at'      => '2019-05-28 16:07:09',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            35  =>
            array(
                'id'              => 36,
                'name'            => 'Deputy Director Rural Economy & Management',
                'bangla_name'     => 'উপ - পরিচালক ( পল্লী অর্থনীতি ও ব্যবস্থাপনা )',
                'short_name'      => 'DDREM',
                'department_id'   => null,
                'hierarchy_level' => 3,
                'rank_id'         => 1,
                'created_at'      => '2019-05-28 16:07:31',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            36  =>
            array(
                'id'              => 37,
                'name'            => 'Asst. Director Rural Economy & Management',
                'bangla_name'     => 'সহঃ পরিচালক ( পল্লী অর্থনীতি ও ব্যবস্থাপনা  )',
                'short_name'      => 'ADREM',
                'department_id'   => null,
                'hierarchy_level' => 4,
                'rank_id'         => 1,
                'created_at'      => '2019-05-28 16:08:07',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            37  =>
            array(
                'id'              => 38,
                'name'            => 'Joint Director Admin',
                'bangla_name'     => 'যুগ্ম পরিচালক ( প্রশাসন )',
                'short_name'      => 'JDA',
                'department_id'   => null,
                'hierarchy_level' => 2,
                'rank_id'         => 1,
                'created_at'      => '2019-05-29 10:16:24',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            38  =>
            array(
                'id'              => 39,
                'name'            => 'Deputy Director Admin',
                'bangla_name'     => null,
                'short_name'      => 'DDA',
                'department_id'   => null,
                'hierarchy_level' => 0,
                'rank_id'         => 1,
                'created_at'      => '2019-05-29 10:16:52',
                'updated_at'      => '2019-05-29 10:16:52',
                'deleted_at'      => null,
            ),
            39  =>
            array(
                'id'              => 40,
                'name'            => 'Asst. Engineer Admin',
                'bangla_name'     => 'সহঃ প্রকৌশলী ( প্রশাসন )',
                'short_name'      => 'AEA',
                'department_id'   => null,
                'hierarchy_level' => 5,
                'rank_id'         => 1,
                'created_at'      => '2019-05-29 10:17:29',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            40  =>
            array(
                'id'              => 41,
                'name'            => 'Asst. Director Admin',
                'bangla_name'     => 'সহঃ পরিচালক ( প্রশাসন )',
                'short_name'      => 'ADA',
                'department_id'   => null,
                'hierarchy_level' => 4,
                'rank_id'         => 1,
                'created_at'      => '2019-05-29 10:18:09',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            41  =>
            array(
                'id'              => 42,
                'name'            => 'Medical Officer Admin',
                'bangla_name'     => 'মেডিকেল অফিসার ( প্রশাসন )',
                'short_name'      => 'MO',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => 1,
                'created_at'      => '2019-05-29 10:18:32',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            42  =>
            array(
                'id'              => 43,
                'name'            => 'Director of Rural Socio. & Demography',
                'bangla_name'     => 'পরিচালক ( পল্লী সমাজতত্ত্ব ও জনমিতি )',
                'short_name'      => 'DRD',
                'department_id'   => null,
                'hierarchy_level' => 1,
                'rank_id'         => 1,
                'created_at'      => '2019-05-29 11:39:49',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            43  =>
            array(
                'id'              => 44,
                'name'            => 'Joint Director Rural Socio. & Demography',
                'bangla_name'     => 'যুগ্ম পরিচালক ( পল্লী সমাজতত্ত্ব ও জনমিতি )',
                'short_name'      => 'JDRD',
                'department_id'   => null,
                'hierarchy_level' => 2,
                'rank_id'         => 1,
                'created_at'      => '2019-05-29 11:40:47',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            44  =>
            array(
                'id'              => 45,
                'name'            => 'Asst. Director Rural Socio. & Demography',
                'bangla_name'     => 'সহঃ পরিচালক ( পল্লী সমাজতত্ত্ব ও জনমিতি )',
                'short_name'      => 'ADRD',
                'department_id'   => null,
                'hierarchy_level' => 4,
                'rank_id'         => 1,
                'created_at'      => '2019-05-29 11:41:11',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            45  =>
            array(
                'id'              => 46,
                'name'            => 'Director Rural Edu. & Social Dev.',
                'bangla_name'     => 'পরিচালক ( পল্লী শিক্ষা ও সমাজ উন্নয়ন )',
                'short_name'      => 'DRESD',
                'department_id'   => null,
                'hierarchy_level' => 1,
                'rank_id'         => 1,
                'created_at'      => '2019-05-29 11:53:44',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            46  =>
            array(
                'id'              => 47,
                'name'            => 'Joint Director Rural Edu. & Social Dev.',
                'bangla_name'     => 'যুগ্ম পরিচালক ( পল্লী শিক্ষা ও সমাজ উন্নয়ন )',
                'short_name'      => 'JDRESD',
                'department_id'   => null,
                'hierarchy_level' => 2,
                'rank_id'         => 1,
                'created_at'      => '2019-05-29 11:54:05',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            47  =>
            array(
                'id'              => 48,
                'name'            => 'Deputy Director Rural Edu. & Social Dev.',
                'bangla_name'     => 'উপ - পরিচালক ( পল্লী শিক্ষা ও সমাজ উন্নয়ন )',
                'short_name'      => 'DDRESD',
                'department_id'   => null,
                'hierarchy_level' => 3,
                'rank_id'         => 1,
                'created_at'      => '2019-05-29 11:54:22',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            48  =>
            array(
                'id'              => 49,
                'name'            => 'Asst. Director Rural Edu. & Social Dev.',
                'bangla_name'     => 'সহঃ পরিচালক ( পল্লী শিক্ষা ও সমাজ উন্নয়ন )',
                'short_name'      => 'ADRESD',
                'department_id'   => null,
                'hierarchy_level' => 4,
                'rank_id'         => 1,
                'created_at'      => '2019-05-29 11:54:41',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            49  =>
            array(
                'id'              => 50,
                'name'            => 'Director Rural Admin. & Local Gov. (Acting)',
                'bangla_name'     => 'পরিচালক ( পল্লী প্রশাসন ও স্থানীয় সরকার ) - ভারপ্রাপ্ত',
                'short_name'      => 'DRL',
                'department_id'   => null,
                'hierarchy_level' => 1,
                'rank_id'         => 1,
                'created_at'      => '2019-05-29 12:36:55',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            50  =>
            array(
                'id'              => 51,
                'name'            => 'Joint Director Rural Admin. & Local Gov.',
                'bangla_name'     => 'যুগ্ম পরিচালক ( পল্লী প্রশাসন ও স্থানীয় সরকার )',
                'short_name'      => 'JDRL',
                'department_id'   => null,
                'hierarchy_level' => 2,
                'rank_id'         => 1,
                'created_at'      => '2019-05-29 12:37:28',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            51  =>
            array(
                'id'              => 52,
                'name'            => 'Deputy Director Rural Admin. & Local Gov.',
                'bangla_name'     => 'উপ - পরিচালক ( পল্লী প্রশাসন ও স্থানীয় সরকার )',
                'short_name'      => 'DDRL',
                'department_id'   => null,
                'hierarchy_level' => 3,
                'rank_id'         => 1,
                'created_at'      => '2019-05-29 12:37:51',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            52  =>
            array(
                'id'              => 53,
                'name'            => 'Asst. Director Rural Admin. & Local Gov.',
                'bangla_name'     => 'সহঃ পরিচালক ( পল্লী প্রশাসন ও স্থানীয় সরকার )',
                'short_name'      => 'ADRL',
                'department_id'   => null,
                'hierarchy_level' => 4,
                'rank_id'         => 1,
                'created_at'      => '2019-05-29 12:38:22',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            53  =>
            array(
                'id'              => 54,
                'name'            => 'Estate Come State Officer',
                'bangla_name'     => '',
                'short_name'      => 'ESO',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => 1,
                'created_at'      => '2019-05-29 12:38:22',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            54  =>
            array(
                'id'              => 55,
                'name'            => 'Store Keeper',
                'bangla_name'     => 'ভাণ্ডার রক্ষক',
                'short_name'      => 'STO',
                'department_id'   => null,
                'hierarchy_level' => 28,
                'rank_id'         => 4,
                'created_at'      => '2019-05-29 12:38:22',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            55  =>
            array(
                'id'              => 56,
                'name'            => 'Deputy Director Rural Socio. & Demography',
                'bangla_name'     => 'উপ - পরিচালক ( পল্লী সমাজতত্ত্ব ও জনমিতি )',
                'short_name'      => 'DDRSD',
                'department_id'   => null,
                'hierarchy_level' => 3,
                'rank_id'         => null,
                'created_at'      => '2019-10-03 16:43:02',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            56  =>
            array(
                'id'              => 57,
                'name'            => 'Section Officer',
                'bangla_name'     => 'সেকশন অফিসার',
                'short_name'      => 'SO',
                'department_id'   => null,
                'hierarchy_level' => 8,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:02:09',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            57  =>
            array(
                'id'              => 58,
                'name'            => 'Sub-Asstt. Engneer',
                'bangla_name'     => 'উপ - সহঃ প্রকৌশলী',
                'short_name'      => 'S.A.E',
                'department_id'   => null,
                'hierarchy_level' => 6,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:03:58',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            58  =>
            array(
                'id'              => 59,
                'name'            => 'Project Assistant',
                'bangla_name'     => 'প্রকল্প সহকারী',
                'short_name'      => 'PA',
                'department_id'   => null,
                'hierarchy_level' => 9,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:04:52',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            59  =>
            array(
                'id'              => 60,
                'name'            => 'Research Assistant',
                'bangla_name'     => 'গবেষণা সহকারী',
                'short_name'      => 'RA',
                'department_id'   => null,
                'hierarchy_level' => 10,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:05:01',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            60  =>
            array(
                'id'              => 61,
                'name'            => 'Training Assistant',
                'bangla_name'     => 'প্রশিক্ষণ সহকারী',
                'short_name'      => 'TA',
                'department_id'   => null,
                'hierarchy_level' => 11,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:05:27',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            61  =>
            array(
                'id'              => 62,
                'name'            => 'Section Assistant',
                'bangla_name'     => 'শাখা সহকারী',
                'short_name'      => 'SA',
                'department_id'   => null,
                'hierarchy_level' => 29,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:06:14',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            62  =>
            array(
                'id'              => 63,
                'name'            => 'Documentation Manager',
                'bangla_name'     => 'ডকুঃ ম্যানেজার',
                'short_name'      => 'DM',
                'department_id'   => null,
                'hierarchy_level' => 22,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:06:37',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            63  =>
            array(
                'id'              => 64,
                'name'            => 'UDA',
                'bangla_name'     => 'উচ্চমান সহকারী',
                'short_name'      => 'UDA',
                'department_id'   => null,
                'hierarchy_level' => 13,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:07:58',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            64  =>
            array(
                'id'              => 65,
                'name'            => 'Library Assistant',
                'bangla_name'     => 'গ্রন্থাগার সহকারী',
                'short_name'      => 'LA',
                'department_id'   => null,
                'hierarchy_level' => 21,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:08:16',
                'updated_at'      => '2020-03-05 18:11:33',
                'deleted_at'      => null,
            ),
            65  =>
            array(
                'id'              => 66,
                'name'            => 'Cashier',
                'bangla_name'     => null,
                'short_name'      => null,
                'department_id'   => null,
                'hierarchy_level' => 0,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:08:30',
                'updated_at'      => '2019-12-03 10:08:30',
                'deleted_at'      => null,
            ),
            66  =>
            array(
                'id'              => 67,
                'name'            => 'Research Supervisor',
                'bangla_name'     => 'গঃ সুঃ ভাইজার',
                'short_name'      => 'RS',
                'department_id'   => null,
                'hierarchy_level' => 15,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:08:51',
                'updated_at'      => '2020-03-05 18:34:23',
                'deleted_at'      => null,
            ),
            67  =>
            array(
                'id'              => 68,
                'name'            => 'Research Tabulator',
                'bangla_name'     => 'গবেঃ টেবুলেটর',
                'short_name'      => 'RT',
                'department_id'   => null,
                'hierarchy_level' => 16,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:09:07',
                'updated_at'      => '2020-03-05 18:34:23',
                'deleted_at'      => null,
            ),
            68  =>
            array(
                'id'              => 69,
                'name'            => 'Short hand-cum-computer operator',
                'bangla_name'     => '',
                'short_name'      => 'SHCO',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:09:52',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            69  =>
            array(
                'id'              => 70,
                'name'            => 'Project Administrator',
                'bangla_name'     => 'প্রকল্প তত্ত্বাবধায়ক',
                'short_name'      => 'PAS',
                'department_id'   => null,
                'hierarchy_level' => 17,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:11:32',
                'updated_at'      => '2020-03-05 18:34:23',
                'deleted_at'      => null,
            ),
            70  =>
            array(
                'id'              => 71,
                'name'            => 'Lady Health Visitor',
                'bangla_name'     => 'লেডী হেলথ ভিজিটর',
                'short_name'      => 'LHV',
                'department_id'   => null,
                'hierarchy_level' => 12,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:11:46',
                'updated_at'      => '2020-03-05 18:34:23',
                'deleted_at'      => null,
            ),
            71  =>
            array(
                'id'              => 72,
                'name'            => 'Lady Health Administrator',
                'bangla_name'     => 'লেডী হেলথ ভিজিটর ( প্রশাসন )',
                'short_name'      => 'LHA',
                'department_id'   => null,
                'hierarchy_level' => 12,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:12:22',
                'updated_at'      => '2020-03-05 18:34:23',
                'deleted_at'      => null,
            ),
            72  =>
            array(
                'id'              => 73,
                'name'            => 'Senior Artist',
                'bangla_name'     => 'চিত্র শিল্পী',
                'short_name'      => 'SART',
                'department_id'   => null,
                'hierarchy_level' => 18,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:12:45',
                'updated_at'      => '2020-03-05 18:34:23',
                'deleted_at'      => null,
            ),
            73  =>
            array(
                'id'              => 74,
                'name'            => 'Junior Artist',
                'bangla_name'     => '',
                'short_name'      => 'JART',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:12:58',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            74  =>
            array(
                'id'              => 75,
                'name'            => 'Transcript Cum Computer Operator',
                'bangla_name'     => '',
                'short_name'      => 'TCCO',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:14:07',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            75  =>
            array(
                'id'              => 76,
                'name'            => 'Pharamcist',
                'bangla_name'     => 'ফার্মাসিস্ট',
                'short_name'      => 'PH',
                'department_id'   => null,
                'hierarchy_level' => 33,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:14:18',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            76  =>
            array(
                'id'              => 77,
                'name'            => 'Equipment Operator',
                'bangla_name'     => 'ইক্যুপমেন্ট অপারেটর',
                'short_name'      => 'EO',
                'department_id'   => null,
                'hierarchy_level' => 31,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:14:39',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            77  =>
            array(
                'id'              => 78,
                'name'            => 'Mechanic',
                'bangla_name'     => '',
                'short_name'      => 'MC',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:14:50',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            78  =>
            array(
                'id'              => 79,
                'name'            => 'Electric Supervisor',
                'bangla_name'     => '',
                'short_name'      => 'ES',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:15:07',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            79  =>
            array(
                'id'              => 80,
                'name'            => 'Plambing Foreman',
                'bangla_name'     => '',
                'short_name'      => 'PF',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:15:20',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            80  =>
            array(
                'id'              => 81,
                'name'            => 'Plamber',
                'bangla_name'     => '',
                'short_name'      => 'PL',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:15:29',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            81  =>
            array(
                'id'              => 82,
                'name'            => 'Electric Artisan',
                'bangla_name'     => '',
                'short_name'      => 'EA',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:16:27',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            82  =>
            array(
                'id'              => 83,
                'name'            => 'Headmaster/Headmistress',
                'bangla_name'     => '',
                'short_name'      => 'HMT',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:17:06',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            83  =>
            array(
                'id'              => 84,
                'name'            => 'Cataloger',
                'bangla_name'     => '',
                'short_name'      => 'CTLG',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:17:45',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            84  =>
            array(
                'id'              => 85,
                'name'            => 'Lower Division Assistant',
                'bangla_name'     => 'নিম্নঃ সহকারী',
                'short_name'      => 'LDA',
                'department_id'   => null,
                'hierarchy_level' => 34,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:19:15',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            85  =>
            array(
                'id'              => 86,
                'name'            => 'Data Collector',
                'bangla_name'     => 'তথ্য সংগ্রহকারী',
                'short_name'      => 'DC',
                'department_id'   => null,
                'hierarchy_level' => 40,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:19:38',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            86  =>
            array(
                'id'              => 87,
                'name'            => 'Lower Division Assistant Cum Computer Operator',
                'bangla_name'     => 'নিম্নঃ সহঃ কম্পিঃ অপাঃ',
                'short_name'      => 'LDACCO',
                'department_id'   => null,
                'hierarchy_level' => 35,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:20:06',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            87  =>
            array(
                'id'              => 88,
                'name'            => 'Demonstrator',
                'bangla_name'     => 'ডেমোনেস্ট্রেটর',
                'short_name'      => 'DMST',
                'department_id'   => null,
                'hierarchy_level' => 46,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:20:23',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            88  =>
            array(
                'id'              => 89,
                'name'            => 'Field Assistant',
                'bangla_name'     => 'মাঠ সহকারী',
                'short_name'      => 'FA',
                'department_id'   => null,
                'hierarchy_level' => 45,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:21:48',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            89  =>
            array(
                'id'              => 90,
                'name'            => 'Salesman',
                'bangla_name'     => '',
                'short_name'      => 'SM',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:23:03',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            90  =>
            array(
                'id'              => 91,
                'name'            => 'Inspector',
                'bangla_name'     => 'পরিদর্শক',
                'short_name'      => 'IP',
                'department_id'   => null,
                'hierarchy_level' => 44,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:23:27',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            91  =>
            array(
                'id'              => 92,
                'name'            => 'Telephone Operator',
                'bangla_name'     => '',
                'short_name'      => 'TO',
                'department_id'   => null,
                'hierarchy_level' => 36,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:23:44',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            92  =>
            array(
                'id'              => 93,
                'name'            => 'Receptionist',
                'bangla_name'     => 'অভ্যর্থনাকারী',
                'short_name'      => 'RP',
                'department_id'   => null,
                'hierarchy_level' => 38,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:24:17',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            93  =>
            array(
                'id'              => 94,
                'name'            => 'Task Assistant',
                'bangla_name'     => '',
                'short_name'      => 'TAS',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:24:48',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            94  =>
            array(
                'id'              => 95,
                'name'            => 'Security Inspector',
                'bangla_name'     => 'সিকিউরিটি ইন্সপেক্টর',
                'short_name'      => 'SI',
                'department_id'   => null,
                'hierarchy_level' => 39,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:25:07',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            95  =>
            array(
                'id'              => 96,
                'name'            => 'Meter Reader',
                'bangla_name'     => '',
                'short_name'      => 'MR',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:25:28',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            96  =>
            array(
                'id'              => 97,
                'name'            => 'Assitant Teacher',
                'bangla_name'     => '',
                'short_name'      => 'AT',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:26:18',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            97  =>
            array(
                'id'              => 98,
                'name'            => 'Driver',
                'bangla_name'     => 'ড্রাইভার',
                'short_name'      => 'DR',
                'department_id'   => null,
                'hierarchy_level' => 41,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:26:38',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            98  =>
            array(
                'id'              => 99,
                'name'            => 'Tractor Driver',
                'bangla_name'     => 'ট্রাক্টর ড্রাইভার',
                'short_name'      => 'TD',
                'department_id'   => null,
                'hierarchy_level' => 43,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:27:06',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            99  =>
            array(
                'id'              => 100,
                'name'            => 'Pump Driver',
                'bangla_name'     => 'পাম্প চালক',
                'short_name'      => 'PDR',
                'department_id'   => null,
                'hierarchy_level' => 50,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:58:46',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            100 =>
            array(
                'id'              => 101,
                'name'            => 'Carpenter',
                'bangla_name'     => 'কাঠ মিস্ত্রি',
                'short_name'      => 'CRP',
                'department_id'   => null,
                'hierarchy_level' => 48,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:59:09',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            101 =>
            array(
                'id'              => 102,
                'name'            => 'Assistant Inspector',
                'bangla_name'     => 'সহকারী পরিদর্শক',
                'short_name'      => 'AI',
                'department_id'   => null,
                'hierarchy_level' => 53,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:59:39',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            102 =>
            array(
                'id'              => 103,
                'name'            => 'Muazzin',
                'bangla_name'     => 'মুয়াজ্জিন',
                'short_name'      => 'MZ',
                'department_id'   => null,
                'hierarchy_level' => 52,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 10:59:52',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            103 =>
            array(
                'id'              => 104,
                'name'            => 'Skilled Maintenance Worker',
                'bangla_name'     => 'এস, এম, ডব্লিউ',
                'short_name'      => 'SMW',
                'department_id'   => null,
                'hierarchy_level' => 54,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 11:00:37',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            104 =>
            array(
                'id'              => 105,
                'name'            => 'Guestetner Operator',
                'bangla_name'     => '',
                'short_name'      => 'GO',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 11:00:51',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            105 =>
            array(
                'id'              => 106,
                'name'            => 'Clinic Assitant',
                'bangla_name'     => 'ক্লিনিক সহকারী',
                'short_name'      => 'CA',
                'department_id'   => null,
                'hierarchy_level' => 51,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 11:14:30',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            106 =>
            array(
                'id'              => 107,
                'name'            => 'Main Cook',
                'bangla_name'     => 'প্রধান বাবুর্চি',
                'short_name'      => 'MCK',
                'department_id'   => null,
                'hierarchy_level' => 60,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 11:48:12',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            107 =>
            array(
                'id'              => 108,
                'name'            => 'Organizer',
                'bangla_name'     => 'সংগঠিকা',
                'short_name'      => 'ORG',
                'department_id'   => null,
                'hierarchy_level' => 57,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 11:49:55',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            108 =>
            array(
                'id'              => 109,
                'name'            => 'Cash Sarker',
                'bangla_name'     => '',
                'short_name'      => 'CSK',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 11:50:16',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            109 =>
            array(
                'id'              => 110,
                'name'            => 'Waving Master',
                'bangla_name'     => 'উইভিং মাস্টার',
                'short_name'      => 'WM',
                'department_id'   => null,
                'hierarchy_level' => 59,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 11:50:27',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            110 =>
            array(
                'id'              => 111,
                'name'            => 'Netting Master',
                'bangla_name'     => '',
                'short_name'      => 'NM',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 11:50:37',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            111 =>
            array(
                'id'              => 112,
                'name'            => 'Driver (Tri Wheeler)',
                'bangla_name'     => 'ট্রাইহুইলার ড্রাইভার',
                'short_name'      => 'DRTW',
                'department_id'   => null,
                'hierarchy_level' => 61,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 11:50:57',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            112 =>
            array(
                'id'              => 113,
                'name'            => 'Cook',
                'bangla_name'     => 'পাচক',
                'short_name'      => 'CK',
                'department_id'   => null,
                'hierarchy_level' => 62,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 11:52:53',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            113 =>
            array(
                'id'              => 114,
                'name'            => 'Binder',
                'bangla_name'     => 'বাইন্ডার',
                'short_name'      => 'BD',
                'department_id'   => null,
                'hierarchy_level' => 67,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 11:53:05',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            114 =>
            array(
                'id'              => 115,
                'name'            => 'Office Assistant',
                'bangla_name'     => 'অফিস সহায়ক',
                'short_name'      => 'OA',
                'department_id'   => null,
                'hierarchy_level' => 75,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 11:53:18',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            115 =>
            array(
                'id'              => 116,
                'name'            => 'Sorter',
                'bangla_name'     => 'সর্টার',
                'short_name'      => 'ST',
                'department_id'   => null,
                'hierarchy_level' => 64,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 11:54:05',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            116 =>
            array(
                'id'              => 117,
                'name'            => 'Snack Maker',
                'bangla_name'     => '',
                'short_name'      => 'SMK',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 11:54:59',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            117 =>
            array(
                'id'              => 118,
                'name'            => 'Main Gardener',
                'bangla_name'     => '',
                'short_name'      => 'MG',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-03 11:55:29',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            118 =>
            array(
                'id'              => 119,
                'name'            => 'Main Attendent',
                'bangla_name'     => '',
                'short_name'      => 'MA',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-04 11:03:02',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            119 =>
            array(
                'id'              => 120,
                'name'            => 'Main Security Guard',
                'bangla_name'     => '',
                'short_name'      => 'MSG',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-04 11:03:21',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            120 =>
            array(
                'id'              => 121,
                'name'            => 'Mason',
                'bangla_name'     => 'ম্যাশন',
                'short_name'      => 'MS',
                'department_id'   => null,
                'hierarchy_level' => 49,
                'rank_id'         => null,
                'created_at'      => '2019-12-04 11:03:29',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            121 =>
            array(
                'id'              => 122,
                'name'            => 'Electric Assistant',
                'bangla_name'     => '',
                'short_name'      => 'EAS',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-04 11:03:45',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            122 =>
            array(
                'id'              => 123,
                'name'            => 'Checker',
                'bangla_name'     => 'চেকার',
                'short_name'      => 'CHK',
                'department_id'   => null,
                'hierarchy_level' => 55,
                'rank_id'         => null,
                'created_at'      => '2019-12-04 11:03:58',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            123 =>
            array(
                'id'              => 124,
                'name'            => 'Tea-Man',
                'bangla_name'     => 'টি ম্যান',
                'short_name'      => 'TM',
                'department_id'   => null,
                'hierarchy_level' => 66,
                'rank_id'         => null,
                'created_at'      => '2019-12-04 11:04:07',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            124 =>
            array(
                'id'              => 125,
                'name'            => 'Stitch Master',
                'bangla_name'     => 'সেলাই মাস্টার',
                'short_name'      => 'STM',
                'department_id'   => null,
                'hierarchy_level' => 56,
                'rank_id'         => null,
                'created_at'      => '2019-12-04 11:22:47',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            125 =>
            array(
                'id'              => 126,
                'name'            => 'Assistant Cook',
                'bangla_name'     => 'সহকারী কুক',
                'short_name'      => 'AC',
                'department_id'   => null,
                'hierarchy_level' => 63,
                'rank_id'         => null,
                'created_at'      => '2019-12-04 11:23:38',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            126 =>
            array(
                'id'              => 127,
                'name'            => 'Assistant Snack Maker',
                'bangla_name'     => '',
                'short_name'      => 'ASM',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-04 11:24:09',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            127 =>
            array(
                'id'              => 128,
                'name'            => 'Mason Assitant',
                'bangla_name'     => 'সহঃ মেশন',
                'short_name'      => 'MAS',
                'department_id'   => null,
                'hierarchy_level' => 70,
                'rank_id'         => null,
                'created_at'      => '2019-12-04 11:24:24',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            128 =>
            array(
                'id'              => 129,
                'name'            => 'Plumbing Assitant',
                'bangla_name'     => 'প্লাম্বিং সহকারী',
                'short_name'      => 'PAST',
                'department_id'   => null,
                'hierarchy_level' => 68,
                'rank_id'         => null,
                'created_at'      => '2019-12-04 11:25:31',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            129 =>
            array(
                'id'              => 130,
                'name'            => 'Assitant Carpenter',
                'bangla_name'     => 'সহঃ কাঠমিস্ত্রি',
                'short_name'      => 'ACP',
                'department_id'   => null,
                'hierarchy_level' => 69,
                'rank_id'         => null,
                'created_at'      => '2019-12-04 11:25:44',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            130 =>
            array(
                'id'              => 131,
                'name'            => 'Helper',
                'bangla_name'     => '',
                'short_name'      => 'HP',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-04 11:25:55',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            131 =>
            array(
                'id'              => 132,
                'name'            => 'Gardener',
                'bangla_name'     => 'বাগানমালী',
                'short_name'      => 'GD',
                'department_id'   => null,
                'hierarchy_level' => 71,
                'rank_id'         => null,
                'created_at'      => '2019-12-04 11:27:20',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            132 =>
            array(
                'id'              => 133,
                'name'            => 'Cleaning Stuff',
                'bangla_name'     => 'পরিচ্ছন্নতা কর্মী',
                'short_name'      => 'CS',
                'department_id'   => null,
                'hierarchy_level' => 77,
                'rank_id'         => null,
                'created_at'      => '2019-12-04 11:27:58',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            133 =>
            array(
                'id'              => 134,
                'name'            => 'Security Guard',
                'bangla_name'     => 'নিরাপত্তা প্রহরী',
                'short_name'      => 'SG',
                'department_id'   => null,
                'hierarchy_level' => 76,
                'rank_id'         => null,
                'created_at'      => '2019-12-04 11:30:59',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            134 =>
            array(
                'id'              => 135,
                'name'            => 'Nursemaid',
                'bangla_name'     => '',
                'short_name'      => 'NMD',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-04 11:31:34',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            135 =>
            array(
                'id'              => 136,
                'name'            => 'Midwife',
                'bangla_name'     => 'দাই',
                'short_name'      => 'MW',
                'department_id'   => null,
                'hierarchy_level' => 73,
                'rank_id'         => null,
                'created_at'      => '2019-12-04 11:31:53',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            136 =>
            array(
                'id'              => 137,
                'name'            => 'Scavenger',
                'bangla_name'     => '',
                'short_name'      => 'SVNG',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-04 11:32:20',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            137 =>
            array(
                'id'              => 138,
                'name'            => 'Training Officer',
                'bangla_name'     => '',
                'short_name'      => 'TOC',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-04 11:34:27',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            138 =>
            array(
                'id'              => 139,
                'name'            => 'Stenographer',
                'bangla_name'     => 'স্টেনোগ্রাফার',
                'short_name'      => 'STG',
                'department_id'   => null,
                'hierarchy_level' => 24,
                'rank_id'         => null,
                'created_at'      => '2019-12-05 12:32:41',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            139 =>
            array(
                'id'              => 140,
                'name'            => 'Project Supervisor',
                'bangla_name'     => '',
                'short_name'      => 'PS',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-05 13:04:05',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            140 =>
            array(
                'id'              => 141,
                'name'            => 'Stenotypist',
                'bangla_name'     => 'স্টেনোটাইপিস্ট',
                'short_name'      => 'STT',
                'department_id'   => null,
                'hierarchy_level' => 26,
                'rank_id'         => null,
                'created_at'      => '2019-12-05 14:41:38',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            141 =>
            array(
                'id'              => 142,
                'name'            => 'Work Assistant',
                'bangla_name'     => 'কার্যসহকারী',
                'short_name'      => 'WA',
                'department_id'   => null,
                'hierarchy_level' => 37,
                'rank_id'         => null,
                'created_at'      => '2019-12-08 14:29:51',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            142 =>
            array(
                'id'              => 143,
                'name'            => 'Photographer',
                'bangla_name'     => 'ফটোগ্রাফার',
                'short_name'      => 'PTG',
                'department_id'   => null,
                'hierarchy_level' => 19,
                'rank_id'         => null,
                'created_at'      => '2019-12-10 12:25:51',
                'updated_at'      => '2020-03-05 18:34:24',
                'deleted_at'      => null,
            ),
            143 =>
            array(
                'id'              => 144,
                'name'            => 'Attendent',
                'bangla_name'     => '',
                'short_name'      => 'ATD',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2019-12-15 10:50:52',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            144 =>
            array(
                'id'              => 145,
                'name'            => 'Waiter',
                'bangla_name'     => '',
                'short_name'      => 'WTR',
                'department_id'   => null,
                'hierarchy_level' => 100,
                'rank_id'         => null,
                'created_at'      => '2020-02-09 15:05:16',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),

            145 =>
            array(
                'id'              => 146,
                'name'            => 'Assistant Director',
                'bangla_name'     => 'সহঃ পরিচালক',
                'short_name'      => 'AD',
                'department_id'   => null,
                'hierarchy_level' => 4,
                'rank_id'         => null,
                'created_at'      => '2020-02-09 15:05:16',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            145 =>
            array(
                'id'              => 146,
                'name'            => 'Assistant Director',
                'bangla_name'     => 'সহঃ পরিচালক',
                'short_name'      => 'AD',
                'department_id'   => null,
                'hierarchy_level' => 4,
                'rank_id'         => null,
                'created_at'      => '2020-02-09 15:05:16',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
            146 =>
            array(
                'id'              => 147,
                'name'            => 'Joint Director',
                'bangla_name'     => 'যুগ্ম পরিচালক',
                'short_name'      => 'JD',
                'department_id'   => null,
                'hierarchy_level' => 2,
                'rank_id'         => null,
                'created_at'      => '2020-02-09 15:05:16',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),

            147 =>
            array(
                'id'              => 148,
                'name'            => 'Deputy Director',
                'bangla_name'     => 'উপ - পরিচালক',
                'short_name'      => 'DD',
                'department_id'   => null,
                'hierarchy_level' => 3,
                'rank_id'         => null,
                'created_at'      => '2020-02-09 15:05:16',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),

            148 =>
            array(
                'id'              => 149,
                'name'            => 'Director',
                'bangla_name'     => 'পরিচালক',
                'short_name'      => 'DRTR',
                'department_id'   => null,
                'hierarchy_level' => 1,
                'rank_id'         => null,
                'created_at'      => '2020-02-09 15:05:16',
                'updated_at'      => '2020-03-05 19:36:54',
                'deleted_at'      => null,
            ),
        ));
    }
}
