<?php

use Illuminate\Database\Seeder;

class InventoryItemCategoriesTableSeeder extends Seeder
{
    /**
     * @var \Modules\IMS\Services\InventoryItemCategoryService
     */
    private $inventoryItemCategoryService;

    public function __construct(\Modules\IMS\Services\InventoryItemCategoryService $inventoryItemCategoryService)
    {
        $this->inventoryItemCategoryService = $inventoryItemCategoryService;
    }

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        static $count = 1;

        \DB::table('inventory_item_categories')->delete();

        \DB::table('inventory_item_categories')->insert(array (
            0 =>
                array (
                    'id' => 1,
                    'group_id' => 1,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'সাদা ডিসটেম্পার- বার্জার(রবিয়াল্যাক)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'ড্রাম',
                    'price' => 7,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2020-06-11 14:30:07',
                ),
            1 =>
                array (
                    'id' => 2,
                    'group_id' => 1,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'ক্রীম ডিসটেম্পার- বার্জার(রবিয়াল্যাক)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'ড্রাম',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2020-06-08 21:39:35',
                ),
            2 =>
                array (
                    'id' => 3,
                    'group_id' => 1,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'সাদা ডিসটেম্পার- বার্জার(রবিয়াল্যাক)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'গ্যালন',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            3 =>
                array (
                    'id' => 4,
                    'group_id' => 1,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'ক্রীম ডিসটেম্পার- বার্জার(রবিয়াল্যাক)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'গ্যালন',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            4 =>
                array (
                    'id' => 5,
                    'group_id' => 2,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'সিমেন্ট- (ক্রাউন/স্ক্যান)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'ব্যাগ',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2020-06-08 21:13:21',
                ),
            5 =>
                array (
                    'id' => 6,
                    'group_id' => 3,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'এনামলে পেইন্ট সাদা- বার্জার(রবিয়াল্যাক)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'লিটার',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2020-06-08 21:28:03',
                ),
            6 =>
                array (
                    'id' => 7,
                    'group_id' => 3,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'এনামেল পেইন্ট গোল্ডেন ব্রাউন- বার্জার(রবিয়াল্যাক)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'লিটার',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            7 =>
                array (
                    'id' => 8,
                    'group_id' => 3,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'এনামেল পেইন্ট কালো- বার্জার(রবিয়াল্যাক)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'লিটার',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            8 =>
                array (
                    'id' => 9,
                    'group_id' => 3,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'এনামেল পেইন্ট সাদা- বার্জার(রবিয়াল্যাক)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'গ্যালন',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            9 =>
                array (
                    'id' => 10,
                    'group_id' => 3,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'এনামেল পেইন্ট গোল্ডেন ব্রাউন- বার্জার(রবিয়াল্যাক)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'গ্যালন',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            10 =>
                array (
                    'id' => 11,
                    'group_id' => 3,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'এনামেল পেইন্ট রেড অক্সাইড- বার্জার(রবিয়াল্যাক)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'গ্যালন',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            11 =>
                array (
                    'id' => 12,
                    'group_id' => 3,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'এনামেল পেইন্ট কালো- বার্জার(রবিয়াল্যাক)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'গ্যালন',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            12 =>
                array (
                    'id' => 13,
                    'group_id' => 4,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'W/C  সিলার- বার্জার(রবিয়াল্যাক)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'গ্যালন',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            13 =>
                array (
                    'id' => 14,
                    'group_id' => 4,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'W/C সিলার- বার্জার(রবিয়াল্যাক)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'ড্রাম',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            14 =>
                array (
                    'id' => 15,
                    'group_id' => 4,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'W/C ক্রীম- বার্জার(রবিয়াল্যাক)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'গ্যালন',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            15 =>
                array (
                    'id' => 16,
                    'group_id' => 4,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'W/C ক্রীম- বার্জার(রবিয়াল্যাক)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'ড্রাম',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            16 =>
                array (
                    'id' => 17,
                    'group_id' => 4,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'W/C কালো- বার্জার(রবিয়াল্যাক)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'ড্রাম',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            17 =>
                array (
                    'id' => 18,
                    'group_id' => 5,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'ইনার সিলার- বার্জার(রবিয়াল্যাক)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'গ্যালন',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            18 =>
                array (
                    'id' => 19,
                    'group_id' => 5,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'ইনার সিলার- বার্জার(রবিয়াল্যাক)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'ড্রাম',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            19 =>
                array (
                    'id' => 20,
                    'group_id' => 6,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'লোহার শিরিষ- চাকা মার্কা',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'ডজন',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            20 =>
                array (
                    'id' => 21,
                    'group_id' => 18,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'থিনার( টি-৬)- বার্জার(রবিয়াল্যাক)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'লিটার',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            21 =>
                array (
                    'id' => 22,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'চক পাউডার (২৫ কেজি বস্তা)- উন্নতমানের ',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'বস্তা',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            22 =>
                array (
                    'id' => 23,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'ফুলের ঝাড়ু- উন্নতমানের ',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            23 =>
                array (
                    'id' => 24,
                    'group_id' => 7,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '৪" ব্রাশ (ডাবল)- বার্জার',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            24 =>
                array (
                    'id' => 25,
                    'group_id' => 7,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '১০" রোলার ব্রাশ- সুতার তৈরী/অফিস নমুনা',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            25 =>
                array (
                    'id' => 26,
                    'group_id' => 7,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'লোহার ব্রাশ (প্লাস্টিক বাট)- উন্নতমানের ',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            26 =>
                array (
                    'id' => 27,
                    'group_id' => 7,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '২" ব্রাশ- বার্জার',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            27 =>
                array (
                    'id' => 28,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '৯ ষ্টেপ মই- এ্যালুমিনিয়াম',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            28 =>
                array (
                    'id' => 29,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'হ্যামার ড্রিল (প্লাষ্টিক বডি ২১০০ ওয়াট)- ক্রাউন',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            29 =>
                array (
                    'id' => 30,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'ক্রীম প্লাষ্টিক পেইন্ট- বার্জার(রবিয়াল্যাক)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'গ্যালন',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            30 =>
                array (
                    'id' => 31,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '১ নং গ্লাস সিরিশ- KLING SPOR MADEIN POLAND. PS 33',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'ডজন',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            31 =>
                array (
                    'id' => 32,
                    'group_id' => 8,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '১ পাউন্ড হাতুড়ী- চায়না/কারিগর',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            32 =>
                array (
                    'id' => 33,
                    'group_id' => 8,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '১.৫০ পাউন্ড হাতুড়ী- চায়না/কারিগর',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            33 =>
                array (
                    'id' => 34,
                    'group_id' => 10,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '১২″ বালতি- উন্নতমানের',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            34 =>
                array (
                    'id' => 35,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'সুতলি- উন্নতমানের',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্র্রতি কেজি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            35 =>
                array (
                    'id' => 36,
                    'group_id' => 12,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'কোদাল- মোরগ মার্কা/অফিস নমুনা',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            36 =>
                array (
                    'id' => 37,
                    'group_id' => 13,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '.৭৫″ হুইজ পাইপ- আরএফএল',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতি ফুট',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            37 =>
                array (
                    'id' => 38,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'হ্যাজ হেন্ডেল (সাইজ ১০″)- এস.এস/ অফিস নমুনা',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            38 =>
                array (
                    'id' => 39,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '.৭৫″ গোমাটাকা- চায়না',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতি প্যাকেট',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            39 =>
                array (
                    'id' => 40,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '৬” হাতল (সাদা)- চায়না',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            40 =>
                array (
                    'id' => 41,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'গ্লাস পুটিং- কুরিয়ান বা এম.আর',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতি কেজি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            41 =>
                array (
                    'id' => 42,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'প্লাষ্টিক মসকিউটো নেট (৬′ ফুট প্রস্থ) ১০০ ফুট লম্বা- চায়না',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতি রোল',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            42 =>
                array (
                    'id' => 43,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'ইয়েল লক (১০″ সাইজ)- বিকার্স (ছোট) / অফিস নমুনা',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            43 =>
                array (
                    'id' => 44,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'কারফা- উন্নত মানের',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'কেজি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            44 =>
                array (
                    'id' => 45,
                    'group_id' => 9,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '৬″ সিটকিনি- এস. এস/অফিস নমুনা',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            45 =>
                array (
                    'id' => 46,
                    'group_id' => 9,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '৮″ সিটকিনি- এস. এস/অফিস নমুনা',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            46 =>
                array (
                    'id' => 47,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '৬″ রেত- ইন্ডিয়ান',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            47 =>
                array (
                    'id' => 48,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'প্লাস্টিক বোর্ড সাইজ ৮′দ্ধ৪′পুরুত ২.৭৫ মি: মি:- আর. এফ. এল',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            48 =>
                array (
                    'id' => 49,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '১.৫০ ″ তার কাটা চিকন মাথা- চায়না',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতি কেজি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            49 =>
                array (
                    'id' => 50,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '২″ তার কাটা চিকন মাথা- চায়না',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতি কেজি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            50 =>
                array (
                    'id' => 51,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'গ্লাস সিরিশ- KLING SPOR MADE IN POLAND. PS 33',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'ডজন',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            51 =>
                array (
                    'id' => 52,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'মোম- উন্নত মানের',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতি কেজি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            52 =>
                array (
                    'id' => 53,
                    'group_id' => 19,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '৫ এম. এম গ্লাস সাইজ ৬’-০”দ্ধ৪’-০”- নাছির/পি.এইচ.পি',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতি বর্গফুট',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            53 =>
                array (
                    'id' => 54,
                    'group_id' => 19,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '৫ এম. এম গ্লাস সাইজ ৫’-০”দ্ধ৩’-৬”- নাছির/পি.এইচ.পি',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতি বর্গফুট',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            54 =>
                array (
                    'id' => 55,
                    'group_id' => 19,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '৫ এম. এম গ্লাস সাইজ ৪’-০”দ্ধ২’-৬”- নাছির/পি.এইচ.পি',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতি বর্গফুট',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            55 =>
                array (
                    'id' => 56,
                    'group_id' => 19,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '২.৫ এম. এম গ্লাস সাইজ ৪২"দ্ধ৩৬"- নাছির/পি.এইচ.পি',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতি বর্গফুট',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            56 =>
                array (
                    'id' => 57,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'রেড অক্সাইড পাউডার- উন্নত মানের',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতি কেজি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            57 =>
                array (
                    'id' => 58,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'বাটালের বাট- গ্রামীন বাট',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            58 =>
                array (
                    'id' => 59,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'তালা- নিউ সুপার',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            59 =>
                array (
                    'id' => 60,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'ড্রয়ার লক- ক্যামেল',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            60 =>
                array (
                    'id' => 61,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'ফাইল কেবিনেট লক- চায়না',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            61 =>
                array (
                    'id' => 62,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'হেমার ড্রিল (প্লাস্টিক বডি) ২১০০ ওয়াট- ক্রাউন',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            62 =>
                array (
                    'id' => 63,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'কড়া- এস. এস/অফিস নমুনা',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতি জোড়া',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            63 =>
                array (
                    'id' => 64,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'টুলস্ ব্যাগ- চায়না (হার্ডেন)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            64 =>
                array (
                    'id' => 65,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'PNO সুইচ- এম. ই. পি/ ক্লাসিক',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            65 =>
                array (
                    'id' => 66,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'গ্যাং রেগুলেটর, সুইচ  প্লাষ্টিক বোর্ডসহ- এম. ই. পি,/ এনার্জি প্যাক',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            66 =>
                array (
                    'id' => 67,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'মাল্টি কড (৪০*৭৬) ৫গজ তারসহ- চায়না',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            67 =>
                array (
                    'id' => 68,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'ব্রাস ব্র্যাকেট হোল্ডার- চায়না',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            68 =>
                array (
                    'id' => 69,
                    'group_id' => 20,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '১০০ ওয়াট পিন বাল্ব- ফিলিপস/ সুপার ষ্টার',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            69 =>
                array (
                    'id' => 70,
                    'group_id' => 20,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '৬০ ওয়াট পিন বাল্ব- ফিলিপস/সুপার ষ্টার',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            70 =>
                array (
                    'id' => 71,
                    'group_id' => 20,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'টিউব হোল্ডার  ২ পেয়ার- খন্দকার/ এম. ই. পি',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            71 =>
                array (
                    'id' => 72,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '৪০ ওয়াট চক কয়েল- রেসার',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            72 =>
                array (
                    'id' => 73,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'প্লাষ্টিক টেপ- তিসা/ওসাকা',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            73 =>
                array (
                    'id' => 74,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '৫ এমস টাম্বলার সুইচ- এম. ই. পি/এরিকসন',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            74 =>
                array (
                    'id' => 75,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '৫৬″ সিলিং পাখা- আর.এফ.এল/ বি.আর.বি',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            75 =>
                array (
                    'id' => 76,
                    'group_id' => 20,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'টিউব লাইট ফ্রেম - ষ্টীল',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            76 =>
                array (
                    'id' => 77,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '৪০ ওয়াট ষ্টার্টার- ট্রান্সটেক',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            77 =>
                array (
                    'id' => 78,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '২.৫ ক্যাপাসিটর- থাইল্যান্ড',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            78 =>
                array (
                    'id' => 79,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '৬ পিন গ্যাং সুইচ সকেট (১৫ এমস) প্লাষ্টিক বোর্ড সহ- এম.কে/এনার্জি প্যাক',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            79 =>
                array (
                    'id' => 80,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'প্যাডাস্টেল পাখা জি.এফ.সি- (পাকিস্তান)',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            80 =>
                array (
                    'id' => 81,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '৬ পিন কমবাইন্ড সুইচ সকেট (১৫ এমস) - এম. ই. পি',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            81 =>
                array (
                    'id' => 82,
                    'group_id' => 16,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'টেষ্টার- সুপার ষ্টার/ ফিলিপস',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            82 =>
                array (
                    'id' => 83,
                    'group_id' => 15,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'ডাষ্টার- অফিস নমুনা',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            83 =>
                array (
                    'id' => 84,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'জুট (গার্মেন্টস)- অফিস নমুনা',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতি কেজি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            84 =>
                array (
                    'id' => 85,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'প্লাষ্টিক রোফ ফ্লাগ (বড়)- টাইগার',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতি প্যাকেট',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            85 =>
                array (
                    'id' => 86,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '৬০ এমস ব্রেকার   (থ্রি ফেইজ)- এ.বি.বি/লিগ্রেন্ড',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            86 =>
                array (
                    'id' => 87,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => '৫ এমস টু পিন চকেট- এম. ই. পি',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            87 =>
                array (
                    'id' => 88,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'ওয়াল বিট হ্যামার- চায়না',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            88 =>
                array (
                    'id' => 89,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'ডিষ্টিল ওয়াটার (৫লিঃ)- ভলবো',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            89 =>
                array (
                    'id' => 90,
                    'group_id' => NULL,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'কর্ড স্কু  ১.৫০″,  ১.২৫", .৫০″  - চায়না',
                    'short_code' => NULL,
                    'type' => 'temporary asset',
                    'unit' => 'প্রতিটি',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2019-08-22 16:06:59',
                    'updated_at' => '2019-08-22 16:06:59',
                ),
            90 =>
                array (
                    'id' => 91,
                    'group_id' => 14,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'কম্পিউটার (অল ইন ওয়ান)',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'pc',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2020-03-03 03:03:54',
                    'updated_at' => '2020-06-07 20:24:57',
                ),
            91 =>
                array (
                    'id' => 92,
                    'group_id' => 14,
                    'unique_id' => $this->inventoryItemCategoryService->generateUniqueId('inv cat', $count++),
                    'name' => 'কম্পিউটার (ডেস্কটপ)',
                    'short_code' => NULL,
                    'type' => 'fixed asset',
                    'unit' => 'pc',
                    'price' => NULL,
                    'is_active' => 1,
                    'created_at' => '2020-03-03 03:05:55',
                    'updated_at' => '2020-06-07 20:18:52',
                ),
        ));


    }
}
