<?php

use Illuminate\Database\Seeder;

class RoomsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('rooms')->delete();

        \DB::table('rooms')->insert(array(
            0 =>
                array(
                    'id' => 1,
                    'hostel_id' => 1,
                    'room_type_id' => 4,
                    'room_number' => '201',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:01:03',
                    'updated_at' => '2019-07-04 16:01:03',
                    'status' => 'available',
                ),
            1 =>
                array(
                    'id' => 2,
                    'hostel_id' => 1,
                    'room_type_id' => 4,
                    'room_number' => '202',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:01:03',
                    'updated_at' => '2019-07-04 16:01:03',
                    'status' => 'available',
                ),
            2 =>
                array(
                    'id' => 3,
                    'hostel_id' => 1,
                    'room_type_id' => 4,
                    'room_number' => '203',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:01:03',
                    'updated_at' => '2019-07-04 16:01:03',
                    'status' => 'available',
                ),
            3 =>
                array(
                    'id' => 4,
                    'hostel_id' => 1,
                    'room_type_id' => 4,
                    'room_number' => '204',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:01:03',
                    'updated_at' => '2019-07-04 16:01:03',
                    'status' => 'available',
                ),
            4 =>
                array(
                    'id' => 5,
                    'hostel_id' => 1,
                    'room_type_id' => 4,
                    'room_number' => '205',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:01:03',
                    'updated_at' => '2019-07-04 16:01:03',
                    'status' => 'available',
                ),
            5 =>
                array(
                    'id' => 6,
                    'hostel_id' => 1,
                    'room_type_id' => 4,
                    'room_number' => '206',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:01:03',
                    'updated_at' => '2019-07-04 16:01:03',
                    'status' => 'available',
                ),
            6 =>
                array(
                    'id' => 7,
                    'hostel_id' => 1,
                    'room_type_id' => 5,
                    'room_number' => '301',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:01:36',
                    'updated_at' => '2019-07-04 16:01:36',
                    'status' => 'available',
                ),
            7 =>
                array(
                    'id' => 8,
                    'hostel_id' => 1,
                    'room_type_id' => 5,
                    'room_number' => '302',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:01:36',
                    'updated_at' => '2019-07-04 16:01:36',
                    'status' => 'available',
                ),
            8 =>
                array(
                    'id' => 9,
                    'hostel_id' => 1,
                    'room_type_id' => 5,
                    'room_number' => '303',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:01:36',
                    'updated_at' => '2019-07-04 16:01:36',
                    'status' => 'available',
                ),
            9 =>
                array(
                    'id' => 10,
                    'hostel_id' => 1,
                    'room_type_id' => 5,
                    'room_number' => '304',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:01:36',
                    'updated_at' => '2019-07-04 16:01:36',
                    'status' => 'available',
                ),
            10 =>
                array(
                    'id' => 11,
                    'hostel_id' => 1,
                    'room_type_id' => 5,
                    'room_number' => '305',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:01:36',
                    'updated_at' => '2019-07-04 16:01:36',
                    'status' => 'available',
                ),
            11 =>
                array(
                    'id' => 12,
                    'hostel_id' => 1,
                    'room_type_id' => 5,
                    'room_number' => '306',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:01:36',
                    'updated_at' => '2019-07-04 16:01:36',
                    'status' => 'available',
                ),
            12 =>
                array(
                    'id' => 13,
                    'hostel_id' => 2,
                    'room_type_id' => 4,
                    'room_number' => '201',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:02:47',
                    'updated_at' => '2019-07-04 16:02:47',
                    'status' => 'available',
                ),
            13 =>
                array(
                    'id' => 14,
                    'hostel_id' => 2,
                    'room_type_id' => 4,
                    'room_number' => '202',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:02:47',
                    'updated_at' => '2019-07-04 16:02:47',
                    'status' => 'available',
                ),
            14 =>
                array(
                    'id' => 15,
                    'hostel_id' => 2,
                    'room_type_id' => 4,
                    'room_number' => '203',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:02:47',
                    'updated_at' => '2019-07-04 16:02:47',
                    'status' => 'available',
                ),
            15 =>
                array(
                    'id' => 16,
                    'hostel_id' => 2,
                    'room_type_id' => 4,
                    'room_number' => '204',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:02:47',
                    'updated_at' => '2019-07-04 16:02:47',
                    'status' => 'available',
                ),
            16 =>
                array(
                    'id' => 17,
                    'hostel_id' => 2,
                    'room_type_id' => 4,
                    'room_number' => '205',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:02:47',
                    'updated_at' => '2019-07-04 16:02:47',
                    'status' => 'available',
                ),
            17 =>
                array(
                    'id' => 18,
                    'hostel_id' => 2,
                    'room_type_id' => 4,
                    'room_number' => '206',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:02:47',
                    'updated_at' => '2019-07-04 16:02:47',
                    'status' => 'available',
                ),
            18 =>
                array(
                    'id' => 19,
                    'hostel_id' => 2,
                    'room_type_id' => 4,
                    'room_number' => '207',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:02:47',
                    'updated_at' => '2019-07-04 16:02:47',
                    'status' => 'available',
                ),
            19 =>
                array(
                    'id' => 20,
                    'hostel_id' => 2,
                    'room_type_id' => 4,
                    'room_number' => '208',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:02:47',
                    'updated_at' => '2019-07-04 16:02:47',
                    'status' => 'available',
                ),
            20 =>
                array(
                    'id' => 21,
                    'hostel_id' => 2,
                    'room_type_id' => 4,
                    'room_number' => '209',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:02:47',
                    'updated_at' => '2019-07-04 16:02:47',
                    'status' => 'available',
                ),
            21 =>
                array(
                    'id' => 22,
                    'hostel_id' => 2,
                    'room_type_id' => 4,
                    'room_number' => '210',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:02:47',
                    'updated_at' => '2019-07-04 16:02:47',
                    'status' => 'available',
                ),
            22 =>
                array(
                    'id' => 23,
                    'hostel_id' => 2,
                    'room_type_id' => 4,
                    'room_number' => '211',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:02:47',
                    'updated_at' => '2019-07-04 16:02:47',
                    'status' => 'available',
                ),
            23 =>
                array(
                    'id' => 24,
                    'hostel_id' => 2,
                    'room_type_id' => 4,
                    'room_number' => '212',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:02:47',
                    'updated_at' => '2019-07-04 16:02:47',
                    'status' => 'available',
                ),
            24 =>
                array(
                    'id' => 25,
                    'hostel_id' => 2,
                    'room_type_id' => 5,
                    'room_number' => '301',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:03:05',
                    'updated_at' => '2019-07-04 16:03:05',
                    'status' => 'available',
                ),
            25 =>
                array(
                    'id' => 26,
                    'hostel_id' => 2,
                    'room_type_id' => 5,
                    'room_number' => '302',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:03:05',
                    'updated_at' => '2019-07-04 16:03:05',
                    'status' => 'available',
                ),
            26 =>
                array(
                    'id' => 27,
                    'hostel_id' => 2,
                    'room_type_id' => 5,
                    'room_number' => '303',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:03:05',
                    'updated_at' => '2019-07-04 16:03:05',
                    'status' => 'available',
                ),
            27 =>
                array(
                    'id' => 28,
                    'hostel_id' => 2,
                    'room_type_id' => 5,
                    'room_number' => '304',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:03:05',
                    'updated_at' => '2019-07-04 16:03:05',
                    'status' => 'available',
                ),
            28 =>
                array(
                    'id' => 29,
                    'hostel_id' => 2,
                    'room_type_id' => 5,
                    'room_number' => '305',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:03:05',
                    'updated_at' => '2019-07-04 16:03:05',
                    'status' => 'available',
                ),
            29 =>
                array(
                    'id' => 30,
                    'hostel_id' => 2,
                    'room_type_id' => 5,
                    'room_number' => '306',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:03:05',
                    'updated_at' => '2019-07-04 16:03:05',
                    'status' => 'available',
                ),
            30 =>
                array(
                    'id' => 31,
                    'hostel_id' => 2,
                    'room_type_id' => 5,
                    'room_number' => '307',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:03:05',
                    'updated_at' => '2019-07-04 16:03:05',
                    'status' => 'available',
                ),
            31 =>
                array(
                    'id' => 32,
                    'hostel_id' => 2,
                    'room_type_id' => 5,
                    'room_number' => '308',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:03:05',
                    'updated_at' => '2019-07-04 16:03:05',
                    'status' => 'available',
                ),
            32 =>
                array(
                    'id' => 33,
                    'hostel_id' => 2,
                    'room_type_id' => 5,
                    'room_number' => '309',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:03:05',
                    'updated_at' => '2019-07-04 16:03:05',
                    'status' => 'available',
                ),
            33 =>
                array(
                    'id' => 34,
                    'hostel_id' => 2,
                    'room_type_id' => 5,
                    'room_number' => '310',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:03:05',
                    'updated_at' => '2019-07-04 16:03:05',
                    'status' => 'available',
                ),
            34 =>
                array(
                    'id' => 35,
                    'hostel_id' => 2,
                    'room_type_id' => 5,
                    'room_number' => '311',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:03:05',
                    'updated_at' => '2019-07-04 16:03:05',
                    'status' => 'available',
                ),
            35 =>
                array(
                    'id' => 36,
                    'hostel_id' => 2,
                    'room_type_id' => 5,
                    'room_number' => '312',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:03:05',
                    'updated_at' => '2019-07-04 16:03:05',
                    'status' => 'available',
                ),
            36 =>
                array(
                    'id' => 37,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '101',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:03:58',
                    'updated_at' => '2019-07-04 16:03:58',
                    'status' => 'available',
                ),
            37 =>
                array(
                    'id' => 38,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '102',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:03:58',
                    'updated_at' => '2019-07-04 16:03:58',
                    'status' => 'available',
                ),
            38 =>
                array(
                    'id' => 39,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '103',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:03:58',
                    'updated_at' => '2019-07-04 16:03:58',
                    'status' => 'available',
                ),
            39 =>
                array(
                    'id' => 40,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '104',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:03:58',
                    'updated_at' => '2019-07-04 16:03:58',
                    'status' => 'available',
                ),
            40 =>
                array(
                    'id' => 41,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '105',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:03:58',
                    'updated_at' => '2019-07-04 16:03:58',
                    'status' => 'available',
                ),
            41 =>
                array(
                    'id' => 42,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '106',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:03:59',
                    'updated_at' => '2019-07-04 16:03:59',
                    'status' => 'available',
                ),
            42 =>
                array(
                    'id' => 43,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '107',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:03:59',
                    'updated_at' => '2019-07-04 16:03:59',
                    'status' => 'available',
                ),
            43 =>
                array(
                    'id' => 44,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '108',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:03:59',
                    'updated_at' => '2019-07-04 16:03:59',
                    'status' => 'available',
                ),
            44 =>
                array(
                    'id' => 45,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '109',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:03:59',
                    'updated_at' => '2019-07-04 16:03:59',
                    'status' => 'available',
                ),
            45 =>
                array(
                    'id' => 46,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '110',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:03:59',
                    'updated_at' => '2019-07-04 16:03:59',
                    'status' => 'available',
                ),
            46 =>
                array(
                    'id' => 47,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '111',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:03:59',
                    'updated_at' => '2019-07-04 16:03:59',
                    'status' => 'available',
                ),
            47 =>
                array(
                    'id' => 48,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '112',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:03:59',
                    'updated_at' => '2019-07-04 16:03:59',
                    'status' => 'available',
                ),
            48 =>
                array(
                    'id' => 49,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '113',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:03:59',
                    'updated_at' => '2019-07-04 16:03:59',
                    'status' => 'available',
                ),
            49 =>
                array(
                    'id' => 50,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '114',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:03:59',
                    'updated_at' => '2019-07-04 16:03:59',
                    'status' => 'available',
                ),
            50 =>
                array(
                    'id' => 51,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '201',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:04:26',
                    'updated_at' => '2019-07-04 16:04:26',
                    'status' => 'available',
                ),
            51 =>
                array(
                    'id' => 52,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '202',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:04:26',
                    'updated_at' => '2019-07-04 16:04:26',
                    'status' => 'available',
                ),
            52 =>
                array(
                    'id' => 53,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '203',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:04:26',
                    'updated_at' => '2019-07-04 16:04:26',
                    'status' => 'available',
                ),
            53 =>
                array(
                    'id' => 54,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '204',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:04:26',
                    'updated_at' => '2019-07-04 16:04:26',
                    'status' => 'available',
                ),
            54 =>
                array(
                    'id' => 55,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '205',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:04:26',
                    'updated_at' => '2019-07-04 16:04:26',
                    'status' => 'available',
                ),
            55 =>
                array(
                    'id' => 56,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '206',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:04:26',
                    'updated_at' => '2019-07-04 16:04:26',
                    'status' => 'available',
                ),
            56 =>
                array(
                    'id' => 57,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '207',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:04:26',
                    'updated_at' => '2019-07-04 16:04:26',
                    'status' => 'available',
                ),
            57 =>
                array(
                    'id' => 58,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '208',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:04:26',
                    'updated_at' => '2019-07-04 16:04:26',
                    'status' => 'available',
                ),
            58 =>
                array(
                    'id' => 59,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '209',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:04:26',
                    'updated_at' => '2019-07-04 16:04:26',
                    'status' => 'available',
                ),
            59 =>
                array(
                    'id' => 60,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '210',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:04:26',
                    'updated_at' => '2019-07-04 16:04:26',
                    'status' => 'available',
                ),
            60 =>
                array(
                    'id' => 61,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '211',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:04:26',
                    'updated_at' => '2019-07-04 16:04:26',
                    'status' => 'available',
                ),
            61 =>
                array(
                    'id' => 62,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '212',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:04:26',
                    'updated_at' => '2019-07-04 16:04:26',
                    'status' => 'available',
                ),
            62 =>
                array(
                    'id' => 63,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '213',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:04:26',
                    'updated_at' => '2019-07-04 16:04:26',
                    'status' => 'available',
                ),
            63 =>
                array(
                    'id' => 64,
                    'hostel_id' => 3,
                    'room_type_id' => 4,
                    'room_number' => '214',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:04:26',
                    'updated_at' => '2019-07-04 16:04:26',
                    'status' => 'available',
                ),
            64 =>
                array(
                    'id' => 65,
                    'hostel_id' => 3,
                    'room_type_id' => 5,
                    'room_number' => '301',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:04:51',
                    'updated_at' => '2019-07-04 16:04:51',
                    'status' => 'available',
                ),
            65 =>
                array(
                    'id' => 66,
                    'hostel_id' => 3,
                    'room_type_id' => 5,
                    'room_number' => '302',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:04:51',
                    'updated_at' => '2019-07-04 16:04:51',
                    'status' => 'available',
                ),
            66 =>
                array(
                    'id' => 67,
                    'hostel_id' => 3,
                    'room_type_id' => 5,
                    'room_number' => '303',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:04:51',
                    'updated_at' => '2019-07-04 16:04:51',
                    'status' => 'available',
                ),
            67 =>
                array(
                    'id' => 68,
                    'hostel_id' => 3,
                    'room_type_id' => 5,
                    'room_number' => '304',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:04:51',
                    'updated_at' => '2019-07-04 16:04:51',
                    'status' => 'available',
                ),
            68 =>
                array(
                    'id' => 69,
                    'hostel_id' => 3,
                    'room_type_id' => 5,
                    'room_number' => '305',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:04:51',
                    'updated_at' => '2019-07-04 16:04:51',
                    'status' => 'available',
                ),
            69 =>
                array(
                    'id' => 70,
                    'hostel_id' => 3,
                    'room_type_id' => 5,
                    'room_number' => '306',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:04:51',
                    'updated_at' => '2019-07-04 16:04:51',
                    'status' => 'available',
                ),
            70 =>
                array(
                    'id' => 71,
                    'hostel_id' => 3,
                    'room_type_id' => 5,
                    'room_number' => '307',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:04:51',
                    'updated_at' => '2019-07-04 16:04:51',
                    'status' => 'available',
                ),
            71 =>
                array(
                    'id' => 72,
                    'hostel_id' => 3,
                    'room_type_id' => 5,
                    'room_number' => '308',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:04:51',
                    'updated_at' => '2019-07-04 16:04:51',
                    'status' => 'available',
                ),
            72 =>
                array(
                    'id' => 73,
                    'hostel_id' => 3,
                    'room_type_id' => 5,
                    'room_number' => '309',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:04:51',
                    'updated_at' => '2019-07-04 16:04:51',
                    'status' => 'available',
                ),
            73 =>
                array(
                    'id' => 74,
                    'hostel_id' => 3,
                    'room_type_id' => 5,
                    'room_number' => '310',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:04:51',
                    'updated_at' => '2019-07-04 16:04:51',
                    'status' => 'available',
                ),
            74 =>
                array(
                    'id' => 75,
                    'hostel_id' => 3,
                    'room_type_id' => 5,
                    'room_number' => '311',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:04:51',
                    'updated_at' => '2019-07-04 16:04:51',
                    'status' => 'available',
                ),
            75 =>
                array(
                    'id' => 76,
                    'hostel_id' => 3,
                    'room_type_id' => 5,
                    'room_number' => '312',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:04:51',
                    'updated_at' => '2019-07-04 16:04:51',
                    'status' => 'available',
                ),
            76 =>
                array(
                    'id' => 77,
                    'hostel_id' => 3,
                    'room_type_id' => 5,
                    'room_number' => '313',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:04:51',
                    'updated_at' => '2019-07-04 16:04:51',
                    'status' => 'available',
                ),
            77 =>
                array(
                    'id' => 78,
                    'hostel_id' => 3,
                    'room_type_id' => 5,
                    'room_number' => '314',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:04:51',
                    'updated_at' => '2019-07-04 16:04:51',
                    'status' => 'available',
                ),
            78 =>
                array(
                    'id' => 79,
                    'hostel_id' => 3,
                    'room_type_id' => 5,
                    'room_number' => '315',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:04:51',
                    'updated_at' => '2019-07-04 16:04:51',
                    'status' => 'available',
                ),
            79 =>
                array(
                    'id' => 88,
                    'hostel_id' => 4,
                    'room_type_id' => 1,
                    'room_number' => '101',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:08:15',
                    'updated_at' => '2019-07-04 16:08:15',
                    'status' => 'available',
                ),
            80 =>
                array(
                    'id' => 89,
                    'hostel_id' => 4,
                    'room_type_id' => 1,
                    'room_number' => '102',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:08:15',
                    'updated_at' => '2019-07-04 16:08:15',
                    'status' => 'available',
                ),
            81 =>
                array(
                    'id' => 90,
                    'hostel_id' => 4,
                    'room_type_id' => 1,
                    'room_number' => '103',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:08:15',
                    'updated_at' => '2019-07-04 16:08:15',
                    'status' => 'available',
                ),
            82 =>
                array(
                    'id' => 91,
                    'hostel_id' => 4,
                    'room_type_id' => 1,
                    'room_number' => '104',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:08:15',
                    'updated_at' => '2019-07-04 16:08:15',
                    'status' => 'available',
                ),
            83 =>
                array(
                    'id' => 92,
                    'hostel_id' => 4,
                    'room_type_id' => 1,
                    'room_number' => '105',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:08:15',
                    'updated_at' => '2019-07-04 16:08:15',
                    'status' => 'available',
                ),
            84 =>
                array(
                    'id' => 93,
                    'hostel_id' => 4,
                    'room_type_id' => 1,
                    'room_number' => '106',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:08:15',
                    'updated_at' => '2019-07-04 16:08:15',
                    'status' => 'available',
                ),
            85 =>
                array(
                    'id' => 94,
                    'hostel_id' => 4,
                    'room_type_id' => 1,
                    'room_number' => '107',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:08:15',
                    'updated_at' => '2019-07-04 16:08:15',
                    'status' => 'available',
                ),
            86 =>
                array(
                    'id' => 95,
                    'hostel_id' => 4,
                    'room_type_id' => 1,
                    'room_number' => '108',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:08:15',
                    'updated_at' => '2019-07-04 16:08:15',
                    'status' => 'available',
                ),
            87 =>
                array(
                    'id' => 96,
                    'hostel_id' => 4,
                    'room_type_id' => 3,
                    'room_number' => '201',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:08:33',
                    'updated_at' => '2019-07-04 16:08:33',
                    'status' => 'available',
                ),
            88 =>
                array(
                    'id' => 97,
                    'hostel_id' => 4,
                    'room_type_id' => 3,
                    'room_number' => '202',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:08:33',
                    'updated_at' => '2019-07-04 16:08:33',
                    'status' => 'available',
                ),
            89 =>
                array(
                    'id' => 98,
                    'hostel_id' => 4,
                    'room_type_id' => 3,
                    'room_number' => '203',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:08:33',
                    'updated_at' => '2019-07-04 16:08:33',
                    'status' => 'available',
                ),
            90 =>
                array(
                    'id' => 99,
                    'hostel_id' => 4,
                    'room_type_id' => 3,
                    'room_number' => '204',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:08:33',
                    'updated_at' => '2019-07-04 16:08:33',
                    'status' => 'available',
                ),
            91 =>
                array(
                    'id' => 100,
                    'hostel_id' => 4,
                    'room_type_id' => 3,
                    'room_number' => '205',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:08:33',
                    'updated_at' => '2019-07-04 16:08:33',
                    'status' => 'available',
                ),
            92 =>
                array(
                    'id' => 101,
                    'hostel_id' => 4,
                    'room_type_id' => 3,
                    'room_number' => '206',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:08:33',
                    'updated_at' => '2019-07-04 16:08:33',
                    'status' => 'available',
                ),
            93 =>
                array(
                    'id' => 102,
                    'hostel_id' => 4,
                    'room_type_id' => 3,
                    'room_number' => '207',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:08:33',
                    'updated_at' => '2019-07-04 16:08:33',
                    'status' => 'available',
                ),
            94 =>
                array(
                    'id' => 103,
                    'hostel_id' => 4,
                    'room_type_id' => 3,
                    'room_number' => '208',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:08:33',
                    'updated_at' => '2019-07-04 16:08:33',
                    'status' => 'available',
                ),
            95 =>
                array(
                    'id' => 104,
                    'hostel_id' => 4,
                    'room_type_id' => 3,
                    'room_number' => '209',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:08:33',
                    'updated_at' => '2019-07-04 16:08:33',
                    'status' => 'available',
                ),
            96 =>
                array(
                    'id' => 105,
                    'hostel_id' => 4,
                    'room_type_id' => 3,
                    'room_number' => '301',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:09:00',
                    'updated_at' => '2019-07-04 16:09:00',
                    'status' => 'available',
                ),
            97 =>
                array(
                    'id' => 106,
                    'hostel_id' => 4,
                    'room_type_id' => 3,
                    'room_number' => '302',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:09:00',
                    'updated_at' => '2019-07-04 16:09:00',
                    'status' => 'available',
                ),
            98 =>
                array(
                    'id' => 107,
                    'hostel_id' => 4,
                    'room_type_id' => 3,
                    'room_number' => '303',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:09:00',
                    'updated_at' => '2019-07-04 16:09:00',
                    'status' => 'available',
                ),
            99 =>
                array(
                    'id' => 108,
                    'hostel_id' => 4,
                    'room_type_id' => 3,
                    'room_number' => '304',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:09:00',
                    'updated_at' => '2019-07-04 16:09:00',
                    'status' => 'available',
                ),
            100 =>
                array(
                    'id' => 109,
                    'hostel_id' => 4,
                    'room_type_id' => 3,
                    'room_number' => '305',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:09:00',
                    'updated_at' => '2019-07-04 16:09:00',
                    'status' => 'available',
                ),
            101 =>
                array(
                    'id' => 110,
                    'hostel_id' => 4,
                    'room_type_id' => 3,
                    'room_number' => '306',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:09:00',
                    'updated_at' => '2019-07-04 16:09:00',
                    'status' => 'available',
                ),
            102 =>
                array(
                    'id' => 111,
                    'hostel_id' => 4,
                    'room_type_id' => 3,
                    'room_number' => '307',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:09:00',
                    'updated_at' => '2019-07-04 16:09:00',
                    'status' => 'available',
                ),
            103 =>
                array(
                    'id' => 112,
                    'hostel_id' => 4,
                    'room_type_id' => 3,
                    'room_number' => '308',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:09:00',
                    'updated_at' => '2019-07-04 16:09:00',
                    'status' => 'available',
                ),
            104 =>
                array(
                    'id' => 113,
                    'hostel_id' => 4,
                    'room_type_id' => 3,
                    'room_number' => '309',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:09:00',
                    'updated_at' => '2019-07-04 16:09:00',
                    'status' => 'available',
                ),
            105 =>
                array(
                    'id' => 114,
                    'hostel_id' => 5,
                    'room_type_id' => 4,
                    'room_number' => '101',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:10:15',
                    'updated_at' => '2019-07-04 16:10:15',
                    'status' => 'available',
                ),
            106 =>
                array(
                    'id' => 115,
                    'hostel_id' => 5,
                    'room_type_id' => 4,
                    'room_number' => '102',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:10:15',
                    'updated_at' => '2019-07-04 16:10:15',
                    'status' => 'available',
                ),
            107 =>
                array(
                    'id' => 116,
                    'hostel_id' => 5,
                    'room_type_id' => 4,
                    'room_number' => '103',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:10:15',
                    'updated_at' => '2019-07-04 16:10:15',
                    'status' => 'available',
                ),
            108 =>
                array(
                    'id' => 117,
                    'hostel_id' => 5,
                    'room_type_id' => 4,
                    'room_number' => '104',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:10:15',
                    'updated_at' => '2019-07-04 16:10:15',
                    'status' => 'available',
                ),
            109 =>
                array(
                    'id' => 118,
                    'hostel_id' => 5,
                    'room_type_id' => 5,
                    'room_number' => '105',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:10:40',
                    'updated_at' => '2019-07-04 16:10:40',
                    'status' => 'available',
                ),
            110 =>
                array(
                    'id' => 119,
                    'hostel_id' => 5,
                    'room_type_id' => 5,
                    'room_number' => '106',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:10:40',
                    'updated_at' => '2019-07-04 16:10:40',
                    'status' => 'available',
                ),
            111 =>
                array(
                    'id' => 120,
                    'hostel_id' => 5,
                    'room_type_id' => 5,
                    'room_number' => '107',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:10:40',
                    'updated_at' => '2019-07-04 16:10:40',
                    'status' => 'available',
                ),
            112 =>
                array(
                    'id' => 121,
                    'hostel_id' => 5,
                    'room_type_id' => 1,
                    'room_number' => '201',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:10:58',
                    'updated_at' => '2019-07-04 16:10:58',
                    'status' => 'available',
                ),
            113 =>
                array(
                    'id' => 122,
                    'hostel_id' => 5,
                    'room_type_id' => 1,
                    'room_number' => '202',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:10:58',
                    'updated_at' => '2019-07-04 16:10:58',
                    'status' => 'available',
                ),
            114 =>
                array(
                    'id' => 123,
                    'hostel_id' => 5,
                    'room_type_id' => 1,
                    'room_number' => '203',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:10:58',
                    'updated_at' => '2019-07-04 16:10:58',
                    'status' => 'available',
                ),
            115 =>
                array(
                    'id' => 124,
                    'hostel_id' => 5,
                    'room_type_id' => 1,
                    'room_number' => '204',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:10:58',
                    'updated_at' => '2019-07-04 16:10:58',
                    'status' => 'available',
                ),
            116 =>
                array(
                    'id' => 125,
                    'hostel_id' => 5,
                    'room_type_id' => 1,
                    'room_number' => '205',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:10:58',
                    'updated_at' => '2019-07-04 16:10:58',
                    'status' => 'available',
                ),
            117 =>
                array(
                    'id' => 126,
                    'hostel_id' => 5,
                    'room_type_id' => 1,
                    'room_number' => '206',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:10:59',
                    'updated_at' => '2019-07-04 16:10:59',
                    'status' => 'available',
                ),
            118 =>
                array(
                    'id' => 127,
                    'hostel_id' => 5,
                    'room_type_id' => 1,
                    'room_number' => '207',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:10:59',
                    'updated_at' => '2019-07-04 16:10:59',
                    'status' => 'available',
                ),
            119 =>
                array(
                    'id' => 128,
                    'hostel_id' => 5,
                    'room_type_id' => 1,
                    'room_number' => '208',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:10:59',
                    'updated_at' => '2019-07-04 16:10:59',
                    'status' => 'available',
                ),
            120 =>
                array(
                    'id' => 129,
                    'hostel_id' => 5,
                    'room_type_id' => 1,
                    'room_number' => '209',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:10:59',
                    'updated_at' => '2019-07-04 16:10:59',
                    'status' => 'available',
                ),
            121 =>
                array(
                    'id' => 130,
                    'hostel_id' => 5,
                    'room_type_id' => 1,
                    'room_number' => '210',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:10:59',
                    'updated_at' => '2019-07-04 16:10:59',
                    'status' => 'available',
                ),
            122 =>
                array(
                    'id' => 131,
                    'hostel_id' => 5,
                    'room_type_id' => 2,
                    'room_number' => '301',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:11:16',
                    'updated_at' => '2019-07-04 16:11:16',
                    'status' => 'available',
                ),
            123 =>
                array(
                    'id' => 132,
                    'hostel_id' => 5,
                    'room_type_id' => 2,
                    'room_number' => '302',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:11:16',
                    'updated_at' => '2019-07-04 16:11:16',
                    'status' => 'available',
                ),
            124 =>
                array(
                    'id' => 133,
                    'hostel_id' => 5,
                    'room_type_id' => 2,
                    'room_number' => '303',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:11:16',
                    'updated_at' => '2019-07-04 16:11:16',
                    'status' => 'available',
                ),
            125 =>
                array(
                    'id' => 134,
                    'hostel_id' => 5,
                    'room_type_id' => 2,
                    'room_number' => '304',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:11:16',
                    'updated_at' => '2019-07-04 16:11:16',
                    'status' => 'available',
                ),
            126 =>
                array(
                    'id' => 135,
                    'hostel_id' => 5,
                    'room_type_id' => 2,
                    'room_number' => '305',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:11:16',
                    'updated_at' => '2019-07-04 16:11:16',
                    'status' => 'available',
                ),
            127 =>
                array(
                    'id' => 136,
                    'hostel_id' => 5,
                    'room_type_id' => 2,
                    'room_number' => '306',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:11:16',
                    'updated_at' => '2019-07-04 16:11:16',
                    'status' => 'available',
                ),
            128 =>
                array(
                    'id' => 137,
                    'hostel_id' => 5,
                    'room_type_id' => 2,
                    'room_number' => '307',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:11:16',
                    'updated_at' => '2019-07-04 16:11:16',
                    'status' => 'available',
                ),
            129 =>
                array(
                    'id' => 138,
                    'hostel_id' => 5,
                    'room_type_id' => 2,
                    'room_number' => '308',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:11:16',
                    'updated_at' => '2019-07-04 16:11:16',
                    'status' => 'available',
                ),
            130 =>
                array(
                    'id' => 139,
                    'hostel_id' => 5,
                    'room_type_id' => 2,
                    'room_number' => '309',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:11:16',
                    'updated_at' => '2019-07-04 16:11:16',
                    'status' => 'available',
                ),
            131 =>
                array(
                    'id' => 140,
                    'hostel_id' => 5,
                    'room_type_id' => 2,
                    'room_number' => '310',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:11:16',
                    'updated_at' => '2019-07-04 16:11:16',
                    'status' => 'available',
                ),
            132 =>
                array(
                    'id' => 141,
                    'hostel_id' => 6,
                    'room_type_id' => 4,
                    'room_number' => '101',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:12:07',
                    'updated_at' => '2019-07-04 16:12:07',
                    'status' => 'available',
                ),
            133 =>
                array(
                    'id' => 142,
                    'hostel_id' => 6,
                    'room_type_id' => 4,
                    'room_number' => '102',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:12:07',
                    'updated_at' => '2019-07-04 16:12:07',
                    'status' => 'available',
                ),
            134 =>
                array(
                    'id' => 143,
                    'hostel_id' => 6,
                    'room_type_id' => 4,
                    'room_number' => '103',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:12:07',
                    'updated_at' => '2019-07-04 16:12:07',
                    'status' => 'available',
                ),
            135 =>
                array(
                    'id' => 144,
                    'hostel_id' => 6,
                    'room_type_id' => 4,
                    'room_number' => '104',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:12:07',
                    'updated_at' => '2019-07-04 16:12:07',
                    'status' => 'available',
                ),
            136 =>
                array(
                    'id' => 145,
                    'hostel_id' => 6,
                    'room_type_id' => 4,
                    'room_number' => '105',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:12:07',
                    'updated_at' => '2019-07-04 16:12:07',
                    'status' => 'available',
                ),
            137 =>
                array(
                    'id' => 146,
                    'hostel_id' => 6,
                    'room_type_id' => 4,
                    'room_number' => '106',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:12:07',
                    'updated_at' => '2019-07-04 16:12:07',
                    'status' => 'available',
                ),
            138 =>
                array(
                    'id' => 147,
                    'hostel_id' => 6,
                    'room_type_id' => 4,
                    'room_number' => '107',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:12:07',
                    'updated_at' => '2019-07-04 16:12:07',
                    'status' => 'available',
                ),
            139 =>
                array(
                    'id' => 148,
                    'hostel_id' => 6,
                    'room_type_id' => 4,
                    'room_number' => '108',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:12:07',
                    'updated_at' => '2019-07-04 16:12:07',
                    'status' => 'available',
                ),
            140 =>
                array(
                    'id' => 149,
                    'hostel_id' => 6,
                    'room_type_id' => 4,
                    'room_number' => '109',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:12:07',
                    'updated_at' => '2019-07-04 16:12:07',
                    'status' => 'available',
                ),
            141 =>
                array(
                    'id' => 150,
                    'hostel_id' => 6,
                    'room_type_id' => 4,
                    'room_number' => '110',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:12:07',
                    'updated_at' => '2019-07-04 16:12:07',
                    'status' => 'available',
                ),
            142 =>
                array(
                    'id' => 151,
                    'hostel_id' => 6,
                    'room_type_id' => 4,
                    'room_number' => '111',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:12:07',
                    'updated_at' => '2019-07-04 16:12:07',
                    'status' => 'available',
                ),
            143 =>
                array(
                    'id' => 152,
                    'hostel_id' => 6,
                    'room_type_id' => 4,
                    'room_number' => '112',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:12:07',
                    'updated_at' => '2019-07-04 16:12:07',
                    'status' => 'available',
                ),
            144 =>
                array(
                    'id' => 153,
                    'hostel_id' => 6,
                    'room_type_id' => 4,
                    'room_number' => '113',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:12:07',
                    'updated_at' => '2019-07-04 16:12:07',
                    'status' => 'available',
                ),
            145 =>
                array(
                    'id' => 154,
                    'hostel_id' => 6,
                    'room_type_id' => 4,
                    'room_number' => '114',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:12:07',
                    'updated_at' => '2019-07-04 16:12:07',
                    'status' => 'available',
                ),
            146 =>
                array(
                    'id' => 155,
                    'hostel_id' => 6,
                    'room_type_id' => 5,
                    'room_number' => '201',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:12:28',
                    'updated_at' => '2019-07-04 16:12:28',
                    'status' => 'available',
                ),
            147 =>
                array(
                    'id' => 156,
                    'hostel_id' => 6,
                    'room_type_id' => 5,
                    'room_number' => '202',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:12:28',
                    'updated_at' => '2019-07-04 16:12:28',
                    'status' => 'available',
                ),
            148 =>
                array(
                    'id' => 157,
                    'hostel_id' => 6,
                    'room_type_id' => 5,
                    'room_number' => '203',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:12:28',
                    'updated_at' => '2019-07-04 16:12:28',
                    'status' => 'available',
                ),
            149 =>
                array(
                    'id' => 158,
                    'hostel_id' => 6,
                    'room_type_id' => 5,
                    'room_number' => '204',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:12:28',
                    'updated_at' => '2019-07-04 16:12:28',
                    'status' => 'available',
                ),
            150 =>
                array(
                    'id' => 159,
                    'hostel_id' => 6,
                    'room_type_id' => 5,
                    'room_number' => '205',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:12:28',
                    'updated_at' => '2019-07-04 16:12:28',
                    'status' => 'available',
                ),
            151 =>
                array(
                    'id' => 160,
                    'hostel_id' => 6,
                    'room_type_id' => 5,
                    'room_number' => '206',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:12:28',
                    'updated_at' => '2019-07-04 16:12:28',
                    'status' => 'available',
                ),
            152 =>
                array(
                    'id' => 161,
                    'hostel_id' => 6,
                    'room_type_id' => 5,
                    'room_number' => '207',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:12:28',
                    'updated_at' => '2019-07-04 16:12:28',
                    'status' => 'available',
                ),
            153 =>
                array(
                    'id' => 162,
                    'hostel_id' => 6,
                    'room_type_id' => 5,
                    'room_number' => '208',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:12:28',
                    'updated_at' => '2019-07-04 16:12:28',
                    'status' => 'available',
                ),
            154 =>
                array(
                    'id' => 163,
                    'hostel_id' => 6,
                    'room_type_id' => 5,
                    'room_number' => '209',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:12:28',
                    'updated_at' => '2019-07-04 16:12:28',
                    'status' => 'available',
                ),
            155 =>
                array(
                    'id' => 164,
                    'hostel_id' => 6,
                    'room_type_id' => 5,
                    'room_number' => '210',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:12:28',
                    'updated_at' => '2019-07-04 16:12:28',
                    'status' => 'available',
                ),
            156 =>
                array(
                    'id' => 165,
                    'hostel_id' => 6,
                    'room_type_id' => 5,
                    'room_number' => '211',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:12:28',
                    'updated_at' => '2019-07-04 16:12:28',
                    'status' => 'available',
                ),
            157 =>
                array(
                    'id' => 166,
                    'hostel_id' => 6,
                    'room_type_id' => 5,
                    'room_number' => '212',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:12:28',
                    'updated_at' => '2019-07-04 16:12:28',
                    'status' => 'available',
                ),
            158 =>
                array(
                    'id' => 167,
                    'hostel_id' => 6,
                    'room_type_id' => 5,
                    'room_number' => '213',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:12:28',
                    'updated_at' => '2019-07-04 16:12:28',
                    'status' => 'available',
                ),
            159 =>
                array(
                    'id' => 168,
                    'hostel_id' => 6,
                    'room_type_id' => 5,
                    'room_number' => '214',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:12:28',
                    'updated_at' => '2019-07-04 16:12:28',
                    'status' => 'available',
                ),
            160 =>
                array(
                    'id' => 169,
                    'hostel_id' => 6,
                    'room_type_id' => 4,
                    'room_number' => '301',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:12:46',
                    'updated_at' => '2019-07-04 16:12:46',
                    'status' => 'available',
                ),
            161 =>
                array(
                    'id' => 170,
                    'hostel_id' => 6,
                    'room_type_id' => 4,
                    'room_number' => '302',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:12:46',
                    'updated_at' => '2019-07-04 16:12:46',
                    'status' => 'available',
                ),
            162 =>
                array(
                    'id' => 171,
                    'hostel_id' => 6,
                    'room_type_id' => 4,
                    'room_number' => '303',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:12:46',
                    'updated_at' => '2019-07-04 16:12:46',
                    'status' => 'available',
                ),
            163 =>
                array(
                    'id' => 172,
                    'hostel_id' => 6,
                    'room_type_id' => 4,
                    'room_number' => '304',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:12:46',
                    'updated_at' => '2019-07-04 16:12:46',
                    'status' => 'available',
                ),
            164 =>
                array(
                    'id' => 173,
                    'hostel_id' => 6,
                    'room_type_id' => 4,
                    'room_number' => '305',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:12:46',
                    'updated_at' => '2019-07-04 16:12:46',
                    'status' => 'available',
                ),
            165 =>
                array(
                    'id' => 174,
                    'hostel_id' => 6,
                    'room_type_id' => 4,
                    'room_number' => '306',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:12:46',
                    'updated_at' => '2019-07-04 16:12:46',
                    'status' => 'available',
                ),
            166 =>
                array(
                    'id' => 175,
                    'hostel_id' => 6,
                    'room_type_id' => 4,
                    'room_number' => '307',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:12:46',
                    'updated_at' => '2019-07-04 16:12:46',
                    'status' => 'available',
                ),
            167 =>
                array(
                    'id' => 176,
                    'hostel_id' => 6,
                    'room_type_id' => 5,
                    'room_number' => '308',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:13:01',
                    'updated_at' => '2019-07-04 16:13:01',
                    'status' => 'available',
                ),
            168 =>
                array(
                    'id' => 177,
                    'hostel_id' => 6,
                    'room_type_id' => 5,
                    'room_number' => '309',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:13:01',
                    'updated_at' => '2019-07-04 16:13:01',
                    'status' => 'available',
                ),
            169 =>
                array(
                    'id' => 178,
                    'hostel_id' => 6,
                    'room_type_id' => 5,
                    'room_number' => '310',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:13:01',
                    'updated_at' => '2019-07-04 16:13:01',
                    'status' => 'available',
                ),
            170 =>
                array(
                    'id' => 179,
                    'hostel_id' => 6,
                    'room_type_id' => 5,
                    'room_number' => '311',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:13:01',
                    'updated_at' => '2019-07-04 16:13:01',
                    'status' => 'available',
                ),
            171 =>
                array(
                    'id' => 180,
                    'hostel_id' => 6,
                    'room_type_id' => 5,
                    'room_number' => '312',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:13:01',
                    'updated_at' => '2019-07-04 16:13:01',
                    'status' => 'available',
                ),
            172 =>
                array(
                    'id' => 181,
                    'hostel_id' => 6,
                    'room_type_id' => 5,
                    'room_number' => '313',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:13:01',
                    'updated_at' => '2019-07-04 16:13:01',
                    'status' => 'available',
                ),
            173 =>
                array(
                    'id' => 182,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '101',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:13:56',
                    'updated_at' => '2019-07-04 16:13:56',
                    'status' => 'available',
                ),
            174 =>
                array(
                    'id' => 183,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '102',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:13:56',
                    'updated_at' => '2019-07-04 16:13:56',
                    'status' => 'available',
                ),
            175 =>
                array(
                    'id' => 184,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '103',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:13:56',
                    'updated_at' => '2019-07-04 16:13:56',
                    'status' => 'available',
                ),
            176 =>
                array(
                    'id' => 185,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '104',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:13:56',
                    'updated_at' => '2019-07-04 16:13:56',
                    'status' => 'available',
                ),
            177 =>
                array(
                    'id' => 186,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '105',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:13:56',
                    'updated_at' => '2019-07-04 16:13:56',
                    'status' => 'available',
                ),
            178 =>
                array(
                    'id' => 187,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '106',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:13:56',
                    'updated_at' => '2019-07-04 16:13:56',
                    'status' => 'available',
                ),
            179 =>
                array(
                    'id' => 188,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '107',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:13:56',
                    'updated_at' => '2019-07-04 16:13:56',
                    'status' => 'available',
                ),
            180 =>
                array(
                    'id' => 189,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '201',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:14:16',
                    'updated_at' => '2019-07-04 16:14:16',
                    'status' => 'available',
                ),
            181 =>
                array(
                    'id' => 190,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '202',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:14:16',
                    'updated_at' => '2019-07-04 16:14:16',
                    'status' => 'available',
                ),
            182 =>
                array(
                    'id' => 191,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '203',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:14:16',
                    'updated_at' => '2019-07-04 16:14:16',
                    'status' => 'available',
                ),
            183 =>
                array(
                    'id' => 192,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '204',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:14:16',
                    'updated_at' => '2019-07-04 16:14:16',
                    'status' => 'available',
                ),
            184 =>
                array(
                    'id' => 193,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '205',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:14:16',
                    'updated_at' => '2019-07-04 16:14:16',
                    'status' => 'available',
                ),
            185 =>
                array(
                    'id' => 194,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '206',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:14:16',
                    'updated_at' => '2019-07-04 16:14:16',
                    'status' => 'available',
                ),
            186 =>
                array(
                    'id' => 195,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '207',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:14:16',
                    'updated_at' => '2019-07-04 16:14:16',
                    'status' => 'available',
                ),
            187 =>
                array(
                    'id' => 196,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '208',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:14:16',
                    'updated_at' => '2019-07-04 16:14:16',
                    'status' => 'available',
                ),
            188 =>
                array(
                    'id' => 197,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '209',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:14:16',
                    'updated_at' => '2019-07-04 16:14:16',
                    'status' => 'available',
                ),
            189 =>
                array(
                    'id' => 198,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '210',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:14:16',
                    'updated_at' => '2019-07-04 16:14:16',
                    'status' => 'available',
                ),
            190 =>
                array(
                    'id' => 199,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '301',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:14:28',
                    'updated_at' => '2019-07-04 16:14:28',
                    'status' => 'available',
                ),
            191 =>
                array(
                    'id' => 200,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '302',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:14:28',
                    'updated_at' => '2019-07-04 16:14:28',
                    'status' => 'available',
                ),
            192 =>
                array(
                    'id' => 201,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '303',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:14:28',
                    'updated_at' => '2019-07-04 16:14:28',
                    'status' => 'available',
                ),
            193 =>
                array(
                    'id' => 202,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '304',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:14:28',
                    'updated_at' => '2019-07-04 16:14:28',
                    'status' => 'available',
                ),
            194 =>
                array(
                    'id' => 203,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '305',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:14:28',
                    'updated_at' => '2019-07-04 16:14:28',
                    'status' => 'available',
                ),
            195 =>
                array(
                    'id' => 204,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '306',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:14:28',
                    'updated_at' => '2019-07-04 16:14:28',
                    'status' => 'available',
                ),
            196 =>
                array(
                    'id' => 205,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '307',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:14:28',
                    'updated_at' => '2019-07-04 16:14:28',
                    'status' => 'available',
                ),
            197 =>
                array(
                    'id' => 206,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '308',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:14:28',
                    'updated_at' => '2019-07-04 16:14:28',
                    'status' => 'available',
                ),
            198 =>
                array(
                    'id' => 207,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '309',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:14:28',
                    'updated_at' => '2019-07-04 16:14:28',
                    'status' => 'available',
                ),
            199 =>
                array(
                    'id' => 208,
                    'hostel_id' => 7,
                    'room_type_id' => 1,
                    'room_number' => '310',
                    'floor' => 3,
                    'created_at' => '2019-07-04 16:14:28',
                    'updated_at' => '2019-07-04 16:14:28',
                    'status' => 'available',
                ),
            200 =>
                array(
                    'id' => 209,
                    'hostel_id' => 8,
                    'room_type_id' => 2,
                    'room_number' => '101',
                    'floor' => 1,
                    'created_at' => '2019-07-04 16:15:19',
                    'updated_at' => '2019-07-04 16:15:19',
                    'status' => 'available',
                ),
            201 =>
                array(
                    'id' => 211,
                    'hostel_id' => 9,
                    'room_type_id' => 1,
                    'room_number' => '202',
                    'floor' => 2,
                    'created_at' => '2019-07-04 16:16:29',
                    'updated_at' => '2019-07-04 16:16:29',
                    'status' => 'available',
                ),
            202 =>
                array(
                    'id' => 212,
                    'hostel_id' => 9,
                    'room_type_id' => 2,
                    'room_number' => '201',
                    'floor' => 2,
                    'created_at' => '2019-07-04 17:09:15',
                    'updated_at' => '2019-07-04 17:09:15',
                    'status' => 'available',
                ),
            203 =>
                array(
                    'id' => 213,
                    'hostel_id' => 10,
                    'room_type_id' => 2,
                    'room_number' => '201',
                    'floor' => 2,
                    'created_at' => '2019-07-04 17:10:22',
                    'updated_at' => '2019-07-04 17:10:22',
                    'status' => 'available',
                ),
        ));


    }
}