<?php

use Illuminate\Database\Seeder;

class ShareRulesDesignationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('share_rules_designations')->delete();

        $jointDirectorDesignation = \Modules\HRM\Entities\Designation::query()->whereShortName('JD')->first();
        $deputyDirectorDesignation = \Modules\HRM\Entities\Designation::query()->whereShortName('DD')->first();
        $assistantDirectorDesignation = \Modules\HRM\Entities\Designation::query()->whereShortName('AD')->first();
        $directorGeneralDesignation = \Modules\HRM\Entities\Designation::query()->whereShortName('DG')->first();
        $assDirectorGeneralDesignation = \Modules\HRM\Entities\Designation::query()->whereShortName('ADG')->first();
        $directorDesignation = \Modules\HRM\Entities\Designation::query()->whereShortName('DRTR')->first();
        $directorAdminDesignation = \Modules\HRM\Entities\Designation::query()->whereShortName('DA')->first();
        // total used degnations for PMS - ADP,JD,DDR,DG,DA and ADG
        $pmsDesignationMap = [
            13 => $assistantDirectorDesignation->id, // adp to AD
            14 => $jointDirectorDesignation->id, // jdp to jd
            15 => $deputyDirectorDesignation->id, // ddp to dd
            16 => $assDirectorGeneralDesignation->id, // ADG to ADG
            17 => $directorGeneralDesignation->id, // DG
            23 => $directorDesignation->id, // DRTR
        ];
        \DB::table('share_rules_designations')->insert(array(
            // research proposal related flor 1- 6
            // Research Brief Sharing Rule - Director research will share with, ADR, JD, DDR, DG and ADG
            0 =>
            array(
                'id' => 1,
                'share_rule_id' => 1,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $assistantDirectorDesignation->id ?? null, // previously 18
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 3,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            1 =>
            array(
                'id' => 2,
                'share_rule_id' => 1,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $jointDirectorDesignation->id ?? null, // previously 19
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 4,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            2 =>
            array(
                'id' => 3,
                'share_rule_id' => 1,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $deputyDirectorDesignation->id ?? null, // previously 20
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 5,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            3 =>
            array(
                'id' => 4,
                'share_rule_id' => 1,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $directorGeneralDesignation->id ?? null, // previously 17
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 6,
                'can_reject' => 1,
                'can_approve' => 1,
                'is_parent' => 0,
            ),
            4 =>
            array(
                'id' => 5,
                'share_rule_id' => 1,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $assDirectorGeneralDesignation->id ?? null, // previously 16
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 7,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            5 =>
            array(
                'id' => 6,
                'share_rule_id' => 1,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $directorDesignation->id ?? null, // previously 22
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 1,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            // ADR will share with DRTR and JDR
            6 =>
            array(
                'id' => 7,
                'share_rule_id' => 3,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $directorDesignation->id ?? null, // previously 22
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 1,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            7 =>
            array(
                'id' => 8,
                'share_rule_id' => 3,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $jointDirectorDesignation->id ?? null, // to joint director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 4,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            // JDR can share with DR, ADR and DDR
            8 =>
            array(
                'id' => 9,
                'share_rule_id' => 4,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $directorDesignation->id ?? null, // to director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 1,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            9 =>
            array(
                'id' => 10,
                'share_rule_id' => 4,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $assistantDirectorDesignation->id ?? null, // to assistant director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 3,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            10 =>
            array(
                'id' => 11,
                'share_rule_id' => 4,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $deputyDirectorDesignation->id ?? null, // t
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 5,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            // ddr can share with JDP and DR
            11 =>
            array(
                'id' => 12,
                'share_rule_id' => 5,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $directorDesignation->id ?? null, // to director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 1,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            12 =>
            array(
                'id' => 13,
                'share_rule_id' => 5,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $jointDirectorDesignation->id ?? null, // to joint director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 4,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            // DG can share with DRTR and ADG
            13 =>
            array(
                'id' => 14,
                'share_rule_id' => 6,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $directorDesignation->id ?? null, // to director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 1,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            14 =>
            array(
                'id' => 15,
                'share_rule_id' => 6,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $assistantDirectorDesignation->id ?? null, // to assist director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 7,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            // ADG can share with DG and DR
            15 =>
            array(
                'id' => 16,
                'share_rule_id' => 7,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $directorGeneralDesignation->id ?? null, // to director general
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 6,
                'can_reject' => 1,
                'can_approve' => 1,
                'is_parent' => 0,
            ),
            16 =>
            array(
                'id' => 17,
                'share_rule_id' => 7,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $directorDesignation->id, // to director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 1,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            // director of research will share with ADR, JD, DDR, DG and ADG
            17 =>
            array(
                'id' => 18,
                'share_rule_id' => 13,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $assistantDirectorDesignation->id ?? null, // to assistant director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 15,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            18 =>
            array(
                'id' => 19,
                'share_rule_id' => 13,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $jointDirectorDesignation->id ?? null, // to join director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 16,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            19 =>
            array(
                'id' => 20,
                'share_rule_id' => 13,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $deputyDirectorDesignation->id ?? null, // to deputy director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 17,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            20 =>
            array(
                'id' => 21,
                'share_rule_id' => 13,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $directorGeneralDesignation->id ?? null, // to director general
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 18,
                'can_reject' => 1,
                'can_approve' => 1,
                'is_parent' => 0,
            ),
            21 =>
            array(
                'id' => 22,
                'share_rule_id' => 13,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $assDirectorGeneralDesignation->id, // to assistant director general
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 19,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            22 =>
            array(
                'id' => 23,
                'share_rule_id' => 13,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $directorDesignation->id ?? null, // to director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 13,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            // Adr will share with DR and JDR
            23 =>
            array(
                'id' => 24,
                'share_rule_id' => 15,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $directorDesignation->id, // to director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 13,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            24 =>
            array(
                'id' => 25,
                'share_rule_id' => 15,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $jointDirectorDesignation->id ?? null, // to joint director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 16,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            // jdr can share with DR , ADR , DDR
            25 =>
            array(
                'id' => 26,
                'share_rule_id' => 16,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $directorDesignation->id ?? null, // to director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 13,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            26 =>
            array(
                'id' => 27,
                'share_rule_id' => 16,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $assistantDirectorDesignation->id ?? null, // to assistant director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 15,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            27 =>
            array(
                'id' => 28,
                'share_rule_id' => 16,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $deputyDirectorDesignation->id ?? null, // to deputy director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 17,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            // ddr can share with JDR and DR
            28 =>
            array(
                'id' => 29,
                'share_rule_id' => 17,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $directorDesignation->id ?? null, // to director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 16,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            29 =>
            array(
                'id' => 30,
                'share_rule_id' => 17,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $jointDirectorDesignation->id ?? null,  // to joint director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 13,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            // DG can share DR, ADR
            30 =>
            array(
                'id' => 31,
                'share_rule_id' => 18,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $directorDesignation->id ?? null, // to director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 13,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            31 =>
            array(
                'id' => 32,
                'share_rule_id' => 18,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $assistantDirectorDesignation->id ?? null, // to assist director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 19,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            // ADG can share with DG and DR
            32 =>
            array(
                'id' => 33,
                'share_rule_id' => 19,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $directorGeneralDesignation->id ?? null, // to director general
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 18,
                'can_reject' => 1,
                'can_approve' => 1,
                'is_parent' => 0,
            ),
            33 =>
            array(
                'id' => 34,
                'share_rule_id' => 19,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $directorDesignation->id ?? null, // to director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 13,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            // project share rule - Director Project can share with ADP, JD,DDR,DG,DA and ADG
            34 =>
            array(
                'id' => 35,
                'share_rule_id' => 2,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[13],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 8,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            35 =>
            array(
                'id' => 36,
                'share_rule_id' => 2,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[14],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 9,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            36 =>
            array(
                'id' => 37,
                'share_rule_id' => 2,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[15],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 10,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            37 =>
            array(
                'id' => 38,
                'share_rule_id' => 2,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[16],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 11,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            38 =>
            array(
                'id' => 39,
                'share_rule_id' => 2,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[17],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 12,
                'can_reject' => 1,
                'can_approve' => 1,
                'is_parent' => 0,
            ),
            39 =>
            array(
                'id' => 40,
                'share_rule_id' => 2,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[23],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 2,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            40 =>
            array(
                'id' => 41,
                'share_rule_id' => 8,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[23],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 2,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            41 =>
            array(
                'id' => 42,
                'share_rule_id' => 8,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[14],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 9,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            42 =>
            array(
                'id' => 43,
                'share_rule_id' => 9,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[23],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 2,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            43 =>
            array(
                'id' => 44,
                'share_rule_id' => 9,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[13],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 8,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            44 =>
            array(
                'id' => 45,
                'share_rule_id' => 9,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[15],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 10,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            45 =>
            array(
                'id' => 46,
                'share_rule_id' => 10,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[23],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 2,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            46 =>
            array(
                'id' => 47,
                'share_rule_id' => 10,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[14],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 9,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            47 =>
            array(
                'id' => 48,
                'share_rule_id' => 11,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[23],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 2,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            48 =>
            array(
                'id' => 49,
                'share_rule_id' => 11,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[17],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 12,
                'can_reject' => 1,
                'can_approve' => 1,
                'is_parent' => 0,
            ),
            49 =>
            array(
                'id' => 50,
                'share_rule_id' => 12,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[16],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 11,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            50 =>
            array(
                'id' => 51,
                'share_rule_id' => 12,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[23],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 2,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            51 =>
            array(
                'id' => 52,
                'share_rule_id' => 14,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[13],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 20,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            52 =>
            array(
                'id' => 53,
                'share_rule_id' => 14,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[14],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 21,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            53 =>
            array(
                'id' => 54,
                'share_rule_id' => 14,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[15],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 22,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            54 =>
            array(
                'id' => 55,
                'share_rule_id' => 14,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[16],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 23,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            55 =>
            array(
                'id' => 56,
                'share_rule_id' => 14,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[17],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 24,
                'can_reject' => 1,
                'can_approve' => 1,
                'is_parent' => 0,
            ),
            56 =>
            array(
                'id' => 57,
                'share_rule_id' => 14,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[23],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 14,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            57 =>
            array(
                'id' => 58,
                'share_rule_id' => 20,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[23],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 14,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            58 =>
            array(
                'id' => 59,
                'share_rule_id' => 20,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[14],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 21,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            59 =>
            array(
                'id' => 60,
                'share_rule_id' => 21,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[23],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 14,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            60 =>
            array(
                'id' => 61,
                'share_rule_id' => 21,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[13],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 20,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            61 =>
            array(
                'id' => 62,
                'share_rule_id' => 21,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[15],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 22,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            62 =>
            array(
                'id' => 63,
                'share_rule_id' => 22,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[23],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 14,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            63 =>
            array(
                'id' => 64,
                'share_rule_id' => 22,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[14],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 21,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            64 =>
            array(
                'id' => 65,
                'share_rule_id' => 23,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[23],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 14,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            65 =>
            array(
                'id' => 66,
                'share_rule_id' => 23,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[17],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 24,
                'can_reject' => 1,
                'can_approve' => 1,
                'is_parent' => 0,
            ),
            66 =>
            array(
                'id' => 67,
                'share_rule_id' => 24,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[16],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 23,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            67 =>
            array(
                'id' => 68,
                'share_rule_id' => 24,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[23],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 14,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            68 =>
            array(
                'id' => 69,
                'share_rule_id' => 25,
                'department_id' => 1,
                'department' => null,
                'designation_id' => 0,
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 26,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            69 =>
            array(
                'id' => 70,
                'share_rule_id' => 25,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $pmsDesignationMap[23],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 25,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            70 =>
            array(
                'id' => 71,
                'share_rule_id' => 25,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $pmsDesignationMap[17],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 26,
                'can_reject' => 1,
                'can_approve' => 1,
                'is_parent' => 0,
            ),
            71 =>
            array(
                'id' => 72,
                'share_rule_id' => 26,
                'department_id' => 1,
                'department' => null,
                'designation_id' => $pmsDesignationMap[23],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 25,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            // DA(brief)-> DIRP and Vice-versa
            72 =>
            array(
                'id' => 73,
                'share_rule_id' => 2,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[23], // director admin is now director
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 28,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            73 =>
            array(
                'id' => 74,
                'share_rule_id' => 28,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[23],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 2,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 1,
            ),

            // DA(details)-> DIRP and Vice-versa
            74 =>
            array(
                'id' => 75,
                'share_rule_id' => 14,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[23],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 29,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            75 =>
            array(
                'id' => 76,
                'share_rule_id' => 29,
                'department_id' => 2,
                'department' => null,
                'designation_id' => $pmsDesignationMap[23],
                'designation' => null,
                'created_at' => null,
                'updated_at' => null,
                'is_sharable' => 1,
                'sharable_id' => 14,
                'can_reject' => 0,
                'can_approve' => 0,
                'is_parent' => 1,
            ),

        ));
    }
}
